package com.wisdom.common.mapper;
import com.wisdom.common.model.KaiPiaoQingKuangBiao_ZongGongSi_ZongJinE_WenJian;


public interface KaiPiaoQingKuangBiao_ZongGongSi_ZongJinE_WenJianMapper {

    KaiPiaoQingKuangBiao_ZongGongSi_ZongJinE_WenJian getKaiPiaoQingKuangBiao_ZongGongSi_ZongJinE_WenJianById(Long id);

    Integer addKaiPiaoQingKuangBiao_ZongGongSi_ZongJinE_WenJian(KaiPiaoQingKuangBiao_ZongGongSi_ZongJinE_WenJian kaiPiaoQingKuangBiao_ZongGongSi_ZongJinE_WenJian);

    Integer updateKaiPiaoQingKuangBiao_ZongGongSi_ZongJinE_WenJian(KaiPiaoQingKuangBiao_ZongGongSi_ZongJinE_WenJian kaiPiaoQingKuangBiao_ZongGongSi_ZongJinE_WenJian);

}
