package com.wisdom.common.model;import java.sql.Timestamp;

public class FinalXiaoXiang implements java.io.Serializable{
private static final long serialVersionUID = 1L;
public FinalXiaoXiang() {}
private Long id;
private Long project_id;
private Double xiaoxiang_17huowujiagong_shuikong_xiaoshoue;
private Double xiaoxiang_17huowujiagong_shukong_xiaoxiangshuie;
private Double xiaoxiang_17huowujiagong_qita_xiaoshoue;
private Double xiaoxiang_17huowujiagong_qita_xiaoxiangshuie;
private Double xiaoxiang_17huowujiagong_weikaipiao_xiaoshoue;
private Double xiaoxiang_17huowujiagong_weikaipiao_xiaoxiangshuie;
private Double xiaoxiang_17huowujiagong_nashui_xiaoshoue;
private Double xiaoxiang_17huowujiagong_nashui_xiaoxiangshuie;
private Double xiaoxiang_17huowujiagong_heji_xiaoshoue;
private Double xiaoxiang_17huowujiagong_heji_xiaoxiangshuie;
private Double xiaoxiang_17fuwuwuxing_shuikong_xiaoshoue;
private Double xiaoxiang_17fuwuwuxing_shuikong_xiaoxiangshuie;
private Double xiaoxiang_17fuwuwuxing_qita_xiaoshoue;
private Double xiaoxiang_17fuwuwuxing_qita_xiaoxiangshuie;
private Double xiaoxiang_17fuwuwuxing_weikaipiao_xiaoshoue;
private Double xiaoxiang_17fuwuwuxing_weikaipiao_xiaoxiangshuie;
private Double xiaoxiang_17fuwuwuxing_nashui_xiaoshoue;
private Double xiaoxiang_17fuwuwuxing_nashui_xiaoxiangshuie;
private Double xiaoxiang_17fuwuwuxing_heji_xiaoshoue;
private Double xiaoxiang_17fuwuwuxing_heji_xiaoxiangshuie;
private Double xiaoxiang_17fuwuwuxing_heji_jiashuiheji;
private Double xiaoxiang_17fuwuwuxing_shijikouchu;
private Double xiaoxiang_17fuwuwuxing_kouchuhou_hanshuixiaoshoue;
private Double xiaoxiang_17fuwuwuxing_kouchuhou_xiaoxianghshuie;
private Double xiaoxiang_13_shuikong_xiaoshoue;
private Double xiaoxiang_13_shuikong_xiaoxiangshuie;
private Double xiaoxiang_13_qita_xiaoshoue;
private Double xiaoxiang_13_qita_xiaoxiangshuie;
private Double xiaoxiang_13_weikaipiao_xiaoshoue;
private Double xiaoxiang_13_weikaipiao_xiaoxiangshuie;
private Double xiaoxiang_13_nashui_xiaoshoue;
private Double xiaoxiang_13_nashui_xiaoxiangshuie;
private Double xiaoxiang_13_heji_xiaoshoue;
private Double xiaoxiang_13_heji_xiaoxiangshuie;
private Double xiaoxiang_11_shuikong_xiaoshoue;
private Double xiaoxiang_11_shuikong_xiaoxiangshuie;
private Double xiaoxiang_11_qita_xiaoshoue;
private Double xiaoxiang_11_qita_xiaoxiangshuie;
private Double xiaoxiang_11_weikaipiao_xiaoshoue;
private Double xiaoxiang_11_weikaipiao_xiaoxiangshuie;
private Double xiaoxiang_11_nashui_xiaoshoue;
private Double xiaoxiang_11_nashui_xiaoxiangshuie;
private Double xiaoxiang_11_heji_xiaoshoue;
private Double xiaoxiang_11_heji_xiaoxiangshuie;
private Double xiaoxiang_11_heji_jiashuiheji;
private Double xiaoxiang_11_shijikouchu;
private Double xiaoxiang_11_kouchuhou_hanshuixiaoshoue;
private Double xiaoxiang_11_kouchuhou_xiaoxiangshuie;
private Double xiaoxiang_6_shuikong_xiaoshoue;
private Double xiaoxiang_6_shuikong_xiaoxiangshuie;
private Double xiaoxiang_6_qita_xiaoshoue;
private Double xiaoxiang_6_qita_xiaoxiangshuie;
private Double xiaoxiang_6_weikaipiao_xiaoshoue;
private Double xiaoxiang_6_weikaipiao_xiaoxiangshoue;
private Double xiaoxiang_6_nashui_xiaoshoue;
private Double xiaoxiang_6_nashui_xiaoxiangshuie;
private Double xiaoxiang_6_heji_xiaoshoue;
private Double xiaoxiang_6_heji_xiaoxiangshuie;
private Double xiaoxiang_6_heji_jiashuiheji;
private Double xiaoxiang_6_shijikouchu;
private Double xiaoxiang_6_kouchuhou_xiaoshoue;
private Double xiaoxiang_6_kouchuhou_xiaoxiangshoue;
private Double yiban_jizhenghuowu_heji_xiaoshoue;
private Double yiban_jizhenghuowu_heji_xiaoxiangshuie;
private Double yiban_jizhengfuwu_heji_xiaoshoue;
private Double yiban_jizhengfuwu_heji_xiaoxiangshuie;
private Double yiban_jizhengfuwu_heji_jiashuiheji;
private Double yiban_jizhengfuwu_shijikouchu;
private Double yiban_jizhengfuwu_kouchuhou_xiaoshoue;
private Double yiban_jizhengfuwu_kouchuhou_xiaoxiangshuie;
private Double xiaoxiang_6zhengshou_shuikong_xiaoshoue;
private Double xiaoxiang_6zhengshou_shuikong_xiaoxiangshuie;
private Double xiaoxiang_6zhengshou_qita_xiaoshoue;
private Double xiaoxiang_6zhengshou_qita_xiaoxiangshuie;
private Double xiaoxiang_6zhengshou_weikaipiao_xiaoshoue;
private Double xiaoxiang_6zhengshou_weikaipiao_xiaoxiangshuie;
private Double xiaoxiang_6zhengshou_heji_xiaoshoue;
private Double xiaoxiang_6zhengshou_heji_xiaoxiangshuie;
private Double xiaoxiang_5huowu_shuikong_xiaoshoue;
private Double xiaoxiang_5huowu_shuikong_xiaoxiangshuie;
private Double xiaoxiang_5huowu_qita_xiaoshoue;
private Double xiaoxiang_5huowu_qita_xiaoxiangshuie;
private Double xiaoxiang_5huowu_weikaipiao_xiaoshoue;
private Double xiaoxiang_5huowu_weikaipiao_xiaoxiangshuie;
private Double xiaoxiang_5huowu_heji_xiaoshoue;
private Double xiaoxiang_5huowu_heji_xiaoxiangshuie;
private Double xiaoxiang_5fuwu_shuikong_xiaoshoue;
private Double xiaoxiang_5fuwu_shuikong_xiaoxiangshuie;
private Double xiaoxiang_5fuwu_qita_xiaoshoue;
private Double xiaoxiang_5fuwu_qita_xiaoxiangshuie;
private Double xiaoxiang_5fuwu_weikaipiao_xiaoshoue;
private Double xiaoxiang_5fuwu_weikaipiao_xiaoxiangshuie;
private Double xiaoxiang_5fuwu_heji_xiaoshoue;
private Double xiaoxiang_5fuwu_heji_xiaoxiangshuie;
private Double xiaoxiang_5fuwu_heji_jiashuiheji;
private Double xiaoxiang_5fuwu_shijikouchu;
private Double xiaoxiang_5fuwu_kouchuhou_xiaoshoue;
private Double xiaoxiang_5fuwu_kouchuhou_xiaoxiangshuie;
private Double xiaoxiang_4_shuikong_xiaoshoue;
private Double xiaoxiang_4_shuikong_xiaoxiangshuie;
private Double xiaoxiang_4_qita_xiaoshoue;
private Double xiaoxiang_4_qita_xiaoxiangshuie;
private Double xiaoxiang_4_weikaipiao_xiaoshoue;
private Double xiaoxiang_4_weikaipiao_xiaoxiangshuie;
private Double xiaoxiang_4_heji_xiaoshoue;
private Double xiaoxiang_4_heji_xiaoxiangshuie;
private Double xiaoxiang_3huowu_shuikong_xiaoshoue;
private Double xiaoxiang_3huowu_shuikong_xiaoxiangshuie;
private Double xiaoxiang_3huowu_qita_xiaoshoue;
private Double xiaoxiang_3huowu_qita_xiaoxiangshuie;
private Double xiaoxiang_3huowu_weikaipiao_xiaoshoue;
private Double xiaoxiang_3huowu_weikaipiao_xiaoxiangshuie;
private Double xiaoxiang_3huowu_heji_xiaoshoue;
private Double xiaoxiang_3huowu_heji_xiaoxiangshuie;
private Double xiaoxiang_3fuwu_shuikong_xiaoshoue;
private Double xiaoxiang_3fuwu_shuikong_xiaoxiangshuie;
private Double xiaoxiang_3fuwu_qita_xiaoshoue;
private Double xiaoxiang_3fuwu_qita_xiaoxiangshuie;
private Double xiaoxiang_3fuwu_weikaipiao_xiaoshoue;
private Double xiaoxiang_3fuwu_weikaipiao_xiaoxiangshuie;
private Double xiaoxiang_3fuwu_heji_xiaoshoue;
private Double xiaoxiang_3fuwu_heji_xiaoxiangshuie;
private Double xiaoxiang_3fuwu_heji_jiashuiheji;
private Double xiaoxiang_3fuwu_kouchuhou_xiaoshoue;
private Double xiaoxiang_3fuwu_kouchuhou_xiaoxiangshuie;
private Double yuzhenglv_a;
private Double yuzhenglv_a_shuikong_xiaoshoue;
private Double yuzhenglv_a_shuikong_xiaoxiangshuie;
private Double yuzhenglv_a_qita_xiaoshoue;
private Double yuzhenglv_a_qita_xiaoxiangshuie;
private Double yuzhenglv_a_weikaipiao_xiaoshoue;
private Double yuzhenglv_a_weikaipiao_xiaoxiangshuie;
private Double yuzhenglv_a_heji_xiaoshoue;
private Double yuzhenglv_a_heji_xiaoxiangshuie;
private Double yuzhenglv_a_heji_jiashuiheji;
private Double yuzhenglv_a_shijikouchu;
private Double yuzhenglv_a_kouchuhou_xiaoshoue;
private Double yuzhenglv_a_kouchuhou_xiaoxiangshuie;
private Double yuzhenglv_b_shuikong_xiaoshoue;
private Double yuzhenglv_b_shuikong_xiaoxiangshuie;
private Double yuzhenglv_b_qita_xiaoshoue;
private Double yuzhenglv_b_qita_xiaoxiangshuie;
private Double yuzhenglv_b_weikaipiao_xiaoshoue;
private Double yuzhenglv_b_weikaipiao_xiaoxiangshuie;
private Double yuzhenglv_b_heji_xiaoshoue;
private Double yuzhenglv_b_heji_xiaoxiangshuie;
private Double yuzhenglv_b_heji_jiashuiheji;
private Double yuzhenglv_b_shijikouchu;
private Double yuzhenglv_b_kouchuhou_xiaoshoue;
private Double yuzhenglv_b_kouchuhou_xiaoxiangshuie;
private Double yuzhenglv_c_shuikong_xiaoshoue;
private Double yuzhenglv_c_shuikong_xiaoxiangshuie;
private Double yuzhenglv_c_qita_xiaoshoue;
private Double yuzhenglv_c_qita_xiaoxiangshuie;
private Double yuzhenglv_c_weikaipiao_xiaoshoue;
private Double yuzhenglv_c_weikaipiao_xiaoxiangshuie;
private Double yuzhenglv_c_heji_xiaoshoue;
private Double yuzhenglv_c_heji_xiaoxiangshuie;
private Double yuzhenglv_c_heji_jiashuiheji;
private Double yuzhenglv_c_shjikouchu;
private Double yuzhenglv_c_kouchuhou_xiaoshoue;
private Double yuzhenglv_c_kouchuhou_xiaoxiangshuie;
private Double jianyi_jizhenghuowu_heji_xiaoshoue;
private Double jianyi_jizhenghuowu_heji_xiaoxiangshuie;
private Double jianyi_jizhengfuwu_heji_xiaoshoue;
private Double jianyi_jizhengfuwu_heji_xiaoxiangshuie;
private Double jianyi_jizhengfuwu_heji_jiashuiheji;
private Double jianyi_jizhengfuwu_shijikouchu;
private Double jianyi_jizhengfuwu_kouchuhou_xiaoshoue;
private Double jianyi_jizhengfuwu_kouchuhou_xiaoxiangshuie;
private Double miandi_huowujiagongxiuli_qita_xiaoshoue;
private Double miandi_huowujiagongxiuli_weikaipiao_xiushoue;
private Double miandi_huowujiagongxiuli_heji_xiaoshoue;
private Double miandi_fu_bu_wu_qita_xiaoshoue;
private Double miandi_fu_bu_wu_weikaipiao_xiaoshoue;
private Double miandi_fu_bu_wu_heji_xiaoshoue;
private Double miandi_fu_bu_wu_heji_jiashuiheji;
private Double miandi_fu_bu_wu_shijikouchu;
private Double miandi_fu_bu_wu_kouchuhou_xiaoshoue;
private Double mianshui_huowujiagong_shuikong_xiaoshoue;
private Double mianshui_huowujiagong_shuikong_xiaoxiangshuie;
private Double mianshui_huowujiagong_qita_xiaoshuoe;
private Double mianshui_huowujiagong_weikaipiao_xiaoshoue;
private Double mianshui_huowujiagong_heji_xiaoshoue;
private Double mianshui_fu_bu_wu_qita_xiaoshoue;
private Double mianshui_fu_bu_wu_weikaipiao_xiaoshoue;
private Double mianshui_fu_bu_wu_heji_xiaoshoue;
private Double mianshui_fu_bu_wu_heji_jiashuiheji;
private Double mianshui_fu_bu_wu_shijikouchu;
private Double mianshui_fu_bu_wu_kouchuhou_xiaoshoue;
public FinalXiaoXiang(Long id, Long project_id, Double xiaoxiang_17huowujiagong_shuikong_xiaoshoue, Double xiaoxiang_17huowujiagong_shukong_xiaoxiangshuie, Double xiaoxiang_17huowujiagong_qita_xiaoshoue, Double xiaoxiang_17huowujiagong_qita_xiaoxiangshuie, Double xiaoxiang_17huowujiagong_weikaipiao_xiaoshoue, Double xiaoxiang_17huowujiagong_weikaipiao_xiaoxiangshuie, Double xiaoxiang_17huowujiagong_nashui_xiaoshoue, Double xiaoxiang_17huowujiagong_nashui_xiaoxiangshuie, Double xiaoxiang_17huowujiagong_heji_xiaoshoue, Double xiaoxiang_17huowujiagong_heji_xiaoxiangshuie, Double xiaoxiang_17fuwuwuxing_shuikong_xiaoshoue, Double xiaoxiang_17fuwuwuxing_shuikong_xiaoxiangshuie, Double xiaoxiang_17fuwuwuxing_qita_xiaoshoue, Double xiaoxiang_17fuwuwuxing_qita_xiaoxiangshuie, Double xiaoxiang_17fuwuwuxing_weikaipiao_xiaoshoue, Double xiaoxiang_17fuwuwuxing_weikaipiao_xiaoxiangshuie, Double xiaoxiang_17fuwuwuxing_nashui_xiaoshoue, Double xiaoxiang_17fuwuwuxing_nashui_xiaoxiangshuie, Double xiaoxiang_17fuwuwuxing_heji_xiaoshoue, Double xiaoxiang_17fuwuwuxing_heji_xiaoxiangshuie, Double xiaoxiang_17fuwuwuxing_heji_jiashuiheji, Double xiaoxiang_17fuwuwuxing_shijikouchu, Double xiaoxiang_17fuwuwuxing_kouchuhou_hanshuixiaoshoue, Double xiaoxiang_17fuwuwuxing_kouchuhou_xiaoxianghshuie, Double xiaoxiang_13_shuikong_xiaoshoue, Double xiaoxiang_13_shuikong_xiaoxiangshuie, Double xiaoxiang_13_qita_xiaoshoue, Double xiaoxiang_13_qita_xiaoxiangshuie, Double xiaoxiang_13_weikaipiao_xiaoshoue, Double xiaoxiang_13_weikaipiao_xiaoxiangshuie, Double xiaoxiang_13_nashui_xiaoshoue, Double xiaoxiang_13_nashui_xiaoxiangshuie, Double xiaoxiang_13_heji_xiaoshoue, Double xiaoxiang_13_heji_xiaoxiangshuie, Double xiaoxiang_11_shuikong_xiaoshoue, Double xiaoxiang_11_shuikong_xiaoxiangshuie, Double xiaoxiang_11_qita_xiaoshoue, Double xiaoxiang_11_qita_xiaoxiangshuie, Double xiaoxiang_11_weikaipiao_xiaoshoue, Double xiaoxiang_11_weikaipiao_xiaoxiangshuie, Double xiaoxiang_11_nashui_xiaoshoue, Double xiaoxiang_11_nashui_xiaoxiangshuie, Double xiaoxiang_11_heji_xiaoshoue, Double xiaoxiang_11_heji_xiaoxiangshuie, Double xiaoxiang_11_heji_jiashuiheji, Double xiaoxiang_11_shijikouchu, Double xiaoxiang_11_kouchuhou_hanshuixiaoshoue, Double xiaoxiang_11_kouchuhou_xiaoxiangshuie, Double xiaoxiang_6_shuikong_xiaoshoue, Double xiaoxiang_6_shuikong_xiaoxiangshuie, Double xiaoxiang_6_qita_xiaoshoue, Double xiaoxiang_6_qita_xiaoxiangshuie, Double xiaoxiang_6_weikaipiao_xiaoshoue, Double xiaoxiang_6_weikaipiao_xiaoxiangshoue, Double xiaoxiang_6_nashui_xiaoshoue, Double xiaoxiang_6_nashui_xiaoxiangshuie, Double xiaoxiang_6_heji_xiaoshoue, Double xiaoxiang_6_heji_xiaoxiangshuie, Double xiaoxiang_6_heji_jiashuiheji, Double xiaoxiang_6_shijikouchu, Double xiaoxiang_6_kouchuhou_xiaoshoue, Double xiaoxiang_6_kouchuhou_xiaoxiangshoue, Double yiban_jizhenghuowu_heji_xiaoshoue, Double yiban_jizhenghuowu_heji_xiaoxiangshuie, Double yiban_jizhengfuwu_heji_xiaoshoue, Double yiban_jizhengfuwu_heji_xiaoxiangshuie, Double yiban_jizhengfuwu_heji_jiashuiheji, Double yiban_jizhengfuwu_shijikouchu, Double yiban_jizhengfuwu_kouchuhou_xiaoshoue, Double yiban_jizhengfuwu_kouchuhou_xiaoxiangshuie, Double xiaoxiang_6zhengshou_shuikong_xiaoshoue, Double xiaoxiang_6zhengshou_shuikong_xiaoxiangshuie, Double xiaoxiang_6zhengshou_qita_xiaoshoue, Double xiaoxiang_6zhengshou_qita_xiaoxiangshuie, Double xiaoxiang_6zhengshou_weikaipiao_xiaoshoue, Double xiaoxiang_6zhengshou_weikaipiao_xiaoxiangshuie, Double xiaoxiang_6zhengshou_heji_xiaoshoue, Double xiaoxiang_6zhengshou_heji_xiaoxiangshuie, Double xiaoxiang_5huowu_shuikong_xiaoshoue, Double xiaoxiang_5huowu_shuikong_xiaoxiangshuie, Double xiaoxiang_5huowu_qita_xiaoshoue, Double xiaoxiang_5huowu_qita_xiaoxiangshuie, Double xiaoxiang_5huowu_weikaipiao_xiaoshoue, Double xiaoxiang_5huowu_weikaipiao_xiaoxiangshuie, Double xiaoxiang_5huowu_heji_xiaoshoue, Double xiaoxiang_5huowu_heji_xiaoxiangshuie, Double xiaoxiang_5fuwu_shuikong_xiaoshoue, Double xiaoxiang_5fuwu_shuikong_xiaoxiangshuie, Double xiaoxiang_5fuwu_qita_xiaoshoue, Double xiaoxiang_5fuwu_qita_xiaoxiangshuie, Double xiaoxiang_5fuwu_weikaipiao_xiaoshoue, Double xiaoxiang_5fuwu_weikaipiao_xiaoxiangshuie, Double xiaoxiang_5fuwu_heji_xiaoshoue, Double xiaoxiang_5fuwu_heji_xiaoxiangshuie, Double xiaoxiang_5fuwu_heji_jiashuiheji, Double xiaoxiang_5fuwu_shijikouchu, Double xiaoxiang_5fuwu_kouchuhou_xiaoshoue, Double xiaoxiang_5fuwu_kouchuhou_xiaoxiangshuie, Double xiaoxiang_4_shuikong_xiaoshoue, Double xiaoxiang_4_shuikong_xiaoxiangshuie, Double xiaoxiang_4_qita_xiaoshoue, Double xiaoxiang_4_qita_xiaoxiangshuie, Double xiaoxiang_4_weikaipiao_xiaoshoue, Double xiaoxiang_4_weikaipiao_xiaoxiangshuie, Double xiaoxiang_4_heji_xiaoshoue, Double xiaoxiang_4_heji_xiaoxiangshuie, Double xiaoxiang_3huowu_shuikong_xiaoshoue, Double xiaoxiang_3huowu_shuikong_xiaoxiangshuie, Double xiaoxiang_3huowu_qita_xiaoshoue, Double xiaoxiang_3huowu_qita_xiaoxiangshuie, Double xiaoxiang_3huowu_weikaipiao_xiaoshoue, Double xiaoxiang_3huowu_weikaipiao_xiaoxiangshuie, Double xiaoxiang_3huowu_heji_xiaoshoue, Double xiaoxiang_3huowu_heji_xiaoxiangshuie, Double xiaoxiang_3fuwu_shuikong_xiaoshoue, Double xiaoxiang_3fuwu_shuikong_xiaoxiangshuie, Double xiaoxiang_3fuwu_qita_xiaoshoue, Double xiaoxiang_3fuwu_qita_xiaoxiangshuie, Double xiaoxiang_3fuwu_weikaipiao_xiaoshoue, Double xiaoxiang_3fuwu_weikaipiao_xiaoxiangshuie, Double xiaoxiang_3fuwu_heji_xiaoshoue, Double xiaoxiang_3fuwu_heji_xiaoxiangshuie, Double xiaoxiang_3fuwu_heji_jiashuiheji, Double xiaoxiang_3fuwu_kouchuhou_xiaoshoue, Double xiaoxiang_3fuwu_kouchuhou_xiaoxiangshuie, Double yuzhenglv_a, Double yuzhenglv_a_shuikong_xiaoshoue, Double yuzhenglv_a_shuikong_xiaoxiangshuie, Double yuzhenglv_a_qita_xiaoshoue, Double yuzhenglv_a_qita_xiaoxiangshuie, Double yuzhenglv_a_weikaipiao_xiaoshoue, Double yuzhenglv_a_weikaipiao_xiaoxiangshuie, Double yuzhenglv_a_heji_xiaoshoue, Double yuzhenglv_a_heji_xiaoxiangshuie, Double yuzhenglv_a_heji_jiashuiheji, Double yuzhenglv_a_shijikouchu, Double yuzhenglv_a_kouchuhou_xiaoshoue, Double yuzhenglv_a_kouchuhou_xiaoxiangshuie, Double yuzhenglv_b_shuikong_xiaoshoue, Double yuzhenglv_b_shuikong_xiaoxiangshuie, Double yuzhenglv_b_qita_xiaoshoue, Double yuzhenglv_b_qita_xiaoxiangshuie, Double yuzhenglv_b_weikaipiao_xiaoshoue, Double yuzhenglv_b_weikaipiao_xiaoxiangshuie, Double yuzhenglv_b_heji_xiaoshoue, Double yuzhenglv_b_heji_xiaoxiangshuie, Double yuzhenglv_b_heji_jiashuiheji, Double yuzhenglv_b_shijikouchu, Double yuzhenglv_b_kouchuhou_xiaoshoue, Double yuzhenglv_b_kouchuhou_xiaoxiangshuie, Double yuzhenglv_c_shuikong_xiaoshoue, Double yuzhenglv_c_shuikong_xiaoxiangshuie, Double yuzhenglv_c_qita_xiaoshoue, Double yuzhenglv_c_qita_xiaoxiangshuie, Double yuzhenglv_c_weikaipiao_xiaoshoue, Double yuzhenglv_c_weikaipiao_xiaoxiangshuie, Double yuzhenglv_c_heji_xiaoshoue, Double yuzhenglv_c_heji_xiaoxiangshuie, Double yuzhenglv_c_heji_jiashuiheji, Double yuzhenglv_c_shjikouchu, Double yuzhenglv_c_kouchuhou_xiaoshoue, Double yuzhenglv_c_kouchuhou_xiaoxiangshuie, Double jianyi_jizhenghuowu_heji_xiaoshoue, Double jianyi_jizhenghuowu_heji_xiaoxiangshuie, Double jianyi_jizhengfuwu_heji_xiaoshoue, Double jianyi_jizhengfuwu_heji_xiaoxiangshuie, Double jianyi_jizhengfuwu_heji_jiashuiheji, Double jianyi_jizhengfuwu_shijikouchu, Double jianyi_jizhengfuwu_kouchuhou_xiaoshoue, Double jianyi_jizhengfuwu_kouchuhou_xiaoxiangshuie, Double miandi_huowujiagongxiuli_qita_xiaoshoue, Double miandi_huowujiagongxiuli_weikaipiao_xiushoue, Double miandi_huowujiagongxiuli_heji_xiaoshoue, Double miandi_fu_bu_wu_qita_xiaoshoue, Double miandi_fu_bu_wu_weikaipiao_xiaoshoue, Double miandi_fu_bu_wu_heji_xiaoshoue, Double miandi_fu_bu_wu_heji_jiashuiheji, Double miandi_fu_bu_wu_shijikouchu, Double miandi_fu_bu_wu_kouchuhou_xiaoshoue, Double mianshui_huowujiagong_shuikong_xiaoshoue, Double mianshui_huowujiagong_shuikong_xiaoxiangshuie, Double mianshui_huowujiagong_qita_xiaoshuoe, Double mianshui_huowujiagong_weikaipiao_xiaoshoue, Double mianshui_huowujiagong_heji_xiaoshoue, Double mianshui_fu_bu_wu_qita_xiaoshoue, Double mianshui_fu_bu_wu_weikaipiao_xiaoshoue, Double mianshui_fu_bu_wu_heji_xiaoshoue, Double mianshui_fu_bu_wu_heji_jiashuiheji, Double mianshui_fu_bu_wu_shijikouchu, Double mianshui_fu_bu_wu_kouchuhou_xiaoshoue) {
this.id=id;
this.project_id=project_id;
this.xiaoxiang_17huowujiagong_shuikong_xiaoshoue=xiaoxiang_17huowujiagong_shuikong_xiaoshoue;
this.xiaoxiang_17huowujiagong_shukong_xiaoxiangshuie=xiaoxiang_17huowujiagong_shukong_xiaoxiangshuie;
this.xiaoxiang_17huowujiagong_qita_xiaoshoue=xiaoxiang_17huowujiagong_qita_xiaoshoue;
this.xiaoxiang_17huowujiagong_qita_xiaoxiangshuie=xiaoxiang_17huowujiagong_qita_xiaoxiangshuie;
this.xiaoxiang_17huowujiagong_weikaipiao_xiaoshoue=xiaoxiang_17huowujiagong_weikaipiao_xiaoshoue;
this.xiaoxiang_17huowujiagong_weikaipiao_xiaoxiangshuie=xiaoxiang_17huowujiagong_weikaipiao_xiaoxiangshuie;
this.xiaoxiang_17huowujiagong_nashui_xiaoshoue=xiaoxiang_17huowujiagong_nashui_xiaoshoue;
this.xiaoxiang_17huowujiagong_nashui_xiaoxiangshuie=xiaoxiang_17huowujiagong_nashui_xiaoxiangshuie;
this.xiaoxiang_17huowujiagong_heji_xiaoshoue=xiaoxiang_17huowujiagong_heji_xiaoshoue;
this.xiaoxiang_17huowujiagong_heji_xiaoxiangshuie=xiaoxiang_17huowujiagong_heji_xiaoxiangshuie;
this.xiaoxiang_17fuwuwuxing_shuikong_xiaoshoue=xiaoxiang_17fuwuwuxing_shuikong_xiaoshoue;
this.xiaoxiang_17fuwuwuxing_shuikong_xiaoxiangshuie=xiaoxiang_17fuwuwuxing_shuikong_xiaoxiangshuie;
this.xiaoxiang_17fuwuwuxing_qita_xiaoshoue=xiaoxiang_17fuwuwuxing_qita_xiaoshoue;
this.xiaoxiang_17fuwuwuxing_qita_xiaoxiangshuie=xiaoxiang_17fuwuwuxing_qita_xiaoxiangshuie;
this.xiaoxiang_17fuwuwuxing_weikaipiao_xiaoshoue=xiaoxiang_17fuwuwuxing_weikaipiao_xiaoshoue;
this.xiaoxiang_17fuwuwuxing_weikaipiao_xiaoxiangshuie=xiaoxiang_17fuwuwuxing_weikaipiao_xiaoxiangshuie;
this.xiaoxiang_17fuwuwuxing_nashui_xiaoshoue=xiaoxiang_17fuwuwuxing_nashui_xiaoshoue;
this.xiaoxiang_17fuwuwuxing_nashui_xiaoxiangshuie=xiaoxiang_17fuwuwuxing_nashui_xiaoxiangshuie;
this.xiaoxiang_17fuwuwuxing_heji_xiaoshoue=xiaoxiang_17fuwuwuxing_heji_xiaoshoue;
this.xiaoxiang_17fuwuwuxing_heji_xiaoxiangshuie=xiaoxiang_17fuwuwuxing_heji_xiaoxiangshuie;
this.xiaoxiang_17fuwuwuxing_heji_jiashuiheji=xiaoxiang_17fuwuwuxing_heji_jiashuiheji;
this.xiaoxiang_17fuwuwuxing_shijikouchu=xiaoxiang_17fuwuwuxing_shijikouchu;
this.xiaoxiang_17fuwuwuxing_kouchuhou_hanshuixiaoshoue=xiaoxiang_17fuwuwuxing_kouchuhou_hanshuixiaoshoue;
this.xiaoxiang_17fuwuwuxing_kouchuhou_xiaoxianghshuie=xiaoxiang_17fuwuwuxing_kouchuhou_xiaoxianghshuie;
this.xiaoxiang_13_shuikong_xiaoshoue=xiaoxiang_13_shuikong_xiaoshoue;
this.xiaoxiang_13_shuikong_xiaoxiangshuie=xiaoxiang_13_shuikong_xiaoxiangshuie;
this.xiaoxiang_13_qita_xiaoshoue=xiaoxiang_13_qita_xiaoshoue;
this.xiaoxiang_13_qita_xiaoxiangshuie=xiaoxiang_13_qita_xiaoxiangshuie;
this.xiaoxiang_13_weikaipiao_xiaoshoue=xiaoxiang_13_weikaipiao_xiaoshoue;
this.xiaoxiang_13_weikaipiao_xiaoxiangshuie=xiaoxiang_13_weikaipiao_xiaoxiangshuie;
this.xiaoxiang_13_nashui_xiaoshoue=xiaoxiang_13_nashui_xiaoshoue;
this.xiaoxiang_13_nashui_xiaoxiangshuie=xiaoxiang_13_nashui_xiaoxiangshuie;
this.xiaoxiang_13_heji_xiaoshoue=xiaoxiang_13_heji_xiaoshoue;
this.xiaoxiang_13_heji_xiaoxiangshuie=xiaoxiang_13_heji_xiaoxiangshuie;
this.xiaoxiang_11_shuikong_xiaoshoue=xiaoxiang_11_shuikong_xiaoshoue;
this.xiaoxiang_11_shuikong_xiaoxiangshuie=xiaoxiang_11_shuikong_xiaoxiangshuie;
this.xiaoxiang_11_qita_xiaoshoue=xiaoxiang_11_qita_xiaoshoue;
this.xiaoxiang_11_qita_xiaoxiangshuie=xiaoxiang_11_qita_xiaoxiangshuie;
this.xiaoxiang_11_weikaipiao_xiaoshoue=xiaoxiang_11_weikaipiao_xiaoshoue;
this.xiaoxiang_11_weikaipiao_xiaoxiangshuie=xiaoxiang_11_weikaipiao_xiaoxiangshuie;
this.xiaoxiang_11_nashui_xiaoshoue=xiaoxiang_11_nashui_xiaoshoue;
this.xiaoxiang_11_nashui_xiaoxiangshuie=xiaoxiang_11_nashui_xiaoxiangshuie;
this.xiaoxiang_11_heji_xiaoshoue=xiaoxiang_11_heji_xiaoshoue;
this.xiaoxiang_11_heji_xiaoxiangshuie=xiaoxiang_11_heji_xiaoxiangshuie;
this.xiaoxiang_11_heji_jiashuiheji=xiaoxiang_11_heji_jiashuiheji;
this.xiaoxiang_11_shijikouchu=xiaoxiang_11_shijikouchu;
this.xiaoxiang_11_kouchuhou_hanshuixiaoshoue=xiaoxiang_11_kouchuhou_hanshuixiaoshoue;
this.xiaoxiang_11_kouchuhou_xiaoxiangshuie=xiaoxiang_11_kouchuhou_xiaoxiangshuie;
this.xiaoxiang_6_shuikong_xiaoshoue=xiaoxiang_6_shuikong_xiaoshoue;
this.xiaoxiang_6_shuikong_xiaoxiangshuie=xiaoxiang_6_shuikong_xiaoxiangshuie;
this.xiaoxiang_6_qita_xiaoshoue=xiaoxiang_6_qita_xiaoshoue;
this.xiaoxiang_6_qita_xiaoxiangshuie=xiaoxiang_6_qita_xiaoxiangshuie;
this.xiaoxiang_6_weikaipiao_xiaoshoue=xiaoxiang_6_weikaipiao_xiaoshoue;
this.xiaoxiang_6_weikaipiao_xiaoxiangshoue=xiaoxiang_6_weikaipiao_xiaoxiangshoue;
this.xiaoxiang_6_nashui_xiaoshoue=xiaoxiang_6_nashui_xiaoshoue;
this.xiaoxiang_6_nashui_xiaoxiangshuie=xiaoxiang_6_nashui_xiaoxiangshuie;
this.xiaoxiang_6_heji_xiaoshoue=xiaoxiang_6_heji_xiaoshoue;
this.xiaoxiang_6_heji_xiaoxiangshuie=xiaoxiang_6_heji_xiaoxiangshuie;
this.xiaoxiang_6_heji_jiashuiheji=xiaoxiang_6_heji_jiashuiheji;
this.xiaoxiang_6_shijikouchu=xiaoxiang_6_shijikouchu;
this.xiaoxiang_6_kouchuhou_xiaoshoue=xiaoxiang_6_kouchuhou_xiaoshoue;
this.xiaoxiang_6_kouchuhou_xiaoxiangshoue=xiaoxiang_6_kouchuhou_xiaoxiangshoue;
this.yiban_jizhenghuowu_heji_xiaoshoue=yiban_jizhenghuowu_heji_xiaoshoue;
this.yiban_jizhenghuowu_heji_xiaoxiangshuie=yiban_jizhenghuowu_heji_xiaoxiangshuie;
this.yiban_jizhengfuwu_heji_xiaoshoue=yiban_jizhengfuwu_heji_xiaoshoue;
this.yiban_jizhengfuwu_heji_xiaoxiangshuie=yiban_jizhengfuwu_heji_xiaoxiangshuie;
this.yiban_jizhengfuwu_heji_jiashuiheji=yiban_jizhengfuwu_heji_jiashuiheji;
this.yiban_jizhengfuwu_shijikouchu=yiban_jizhengfuwu_shijikouchu;
this.yiban_jizhengfuwu_kouchuhou_xiaoshoue=yiban_jizhengfuwu_kouchuhou_xiaoshoue;
this.yiban_jizhengfuwu_kouchuhou_xiaoxiangshuie=yiban_jizhengfuwu_kouchuhou_xiaoxiangshuie;
this.xiaoxiang_6zhengshou_shuikong_xiaoshoue=xiaoxiang_6zhengshou_shuikong_xiaoshoue;
this.xiaoxiang_6zhengshou_shuikong_xiaoxiangshuie=xiaoxiang_6zhengshou_shuikong_xiaoxiangshuie;
this.xiaoxiang_6zhengshou_qita_xiaoshoue=xiaoxiang_6zhengshou_qita_xiaoshoue;
this.xiaoxiang_6zhengshou_qita_xiaoxiangshuie=xiaoxiang_6zhengshou_qita_xiaoxiangshuie;
this.xiaoxiang_6zhengshou_weikaipiao_xiaoshoue=xiaoxiang_6zhengshou_weikaipiao_xiaoshoue;
this.xiaoxiang_6zhengshou_weikaipiao_xiaoxiangshuie=xiaoxiang_6zhengshou_weikaipiao_xiaoxiangshuie;
this.xiaoxiang_6zhengshou_heji_xiaoshoue=xiaoxiang_6zhengshou_heji_xiaoshoue;
this.xiaoxiang_6zhengshou_heji_xiaoxiangshuie=xiaoxiang_6zhengshou_heji_xiaoxiangshuie;
this.xiaoxiang_5huowu_shuikong_xiaoshoue=xiaoxiang_5huowu_shuikong_xiaoshoue;
this.xiaoxiang_5huowu_shuikong_xiaoxiangshuie=xiaoxiang_5huowu_shuikong_xiaoxiangshuie;
this.xiaoxiang_5huowu_qita_xiaoshoue=xiaoxiang_5huowu_qita_xiaoshoue;
this.xiaoxiang_5huowu_qita_xiaoxiangshuie=xiaoxiang_5huowu_qita_xiaoxiangshuie;
this.xiaoxiang_5huowu_weikaipiao_xiaoshoue=xiaoxiang_5huowu_weikaipiao_xiaoshoue;
this.xiaoxiang_5huowu_weikaipiao_xiaoxiangshuie=xiaoxiang_5huowu_weikaipiao_xiaoxiangshuie;
this.xiaoxiang_5huowu_heji_xiaoshoue=xiaoxiang_5huowu_heji_xiaoshoue;
this.xiaoxiang_5huowu_heji_xiaoxiangshuie=xiaoxiang_5huowu_heji_xiaoxiangshuie;
this.xiaoxiang_5fuwu_shuikong_xiaoshoue=xiaoxiang_5fuwu_shuikong_xiaoshoue;
this.xiaoxiang_5fuwu_shuikong_xiaoxiangshuie=xiaoxiang_5fuwu_shuikong_xiaoxiangshuie;
this.xiaoxiang_5fuwu_qita_xiaoshoue=xiaoxiang_5fuwu_qita_xiaoshoue;
this.xiaoxiang_5fuwu_qita_xiaoxiangshuie=xiaoxiang_5fuwu_qita_xiaoxiangshuie;
this.xiaoxiang_5fuwu_weikaipiao_xiaoshoue=xiaoxiang_5fuwu_weikaipiao_xiaoshoue;
this.xiaoxiang_5fuwu_weikaipiao_xiaoxiangshuie=xiaoxiang_5fuwu_weikaipiao_xiaoxiangshuie;
this.xiaoxiang_5fuwu_heji_xiaoshoue=xiaoxiang_5fuwu_heji_xiaoshoue;
this.xiaoxiang_5fuwu_heji_xiaoxiangshuie=xiaoxiang_5fuwu_heji_xiaoxiangshuie;
this.xiaoxiang_5fuwu_heji_jiashuiheji=xiaoxiang_5fuwu_heji_jiashuiheji;
this.xiaoxiang_5fuwu_shijikouchu=xiaoxiang_5fuwu_shijikouchu;
this.xiaoxiang_5fuwu_kouchuhou_xiaoshoue=xiaoxiang_5fuwu_kouchuhou_xiaoshoue;
this.xiaoxiang_5fuwu_kouchuhou_xiaoxiangshuie=xiaoxiang_5fuwu_kouchuhou_xiaoxiangshuie;
this.xiaoxiang_4_shuikong_xiaoshoue=xiaoxiang_4_shuikong_xiaoshoue;
this.xiaoxiang_4_shuikong_xiaoxiangshuie=xiaoxiang_4_shuikong_xiaoxiangshuie;
this.xiaoxiang_4_qita_xiaoshoue=xiaoxiang_4_qita_xiaoshoue;
this.xiaoxiang_4_qita_xiaoxiangshuie=xiaoxiang_4_qita_xiaoxiangshuie;
this.xiaoxiang_4_weikaipiao_xiaoshoue=xiaoxiang_4_weikaipiao_xiaoshoue;
this.xiaoxiang_4_weikaipiao_xiaoxiangshuie=xiaoxiang_4_weikaipiao_xiaoxiangshuie;
this.xiaoxiang_4_heji_xiaoshoue=xiaoxiang_4_heji_xiaoshoue;
this.xiaoxiang_4_heji_xiaoxiangshuie=xiaoxiang_4_heji_xiaoxiangshuie;
this.xiaoxiang_3huowu_shuikong_xiaoshoue=xiaoxiang_3huowu_shuikong_xiaoshoue;
this.xiaoxiang_3huowu_shuikong_xiaoxiangshuie=xiaoxiang_3huowu_shuikong_xiaoxiangshuie;
this.xiaoxiang_3huowu_qita_xiaoshoue=xiaoxiang_3huowu_qita_xiaoshoue;
this.xiaoxiang_3huowu_qita_xiaoxiangshuie=xiaoxiang_3huowu_qita_xiaoxiangshuie;
this.xiaoxiang_3huowu_weikaipiao_xiaoshoue=xiaoxiang_3huowu_weikaipiao_xiaoshoue;
this.xiaoxiang_3huowu_weikaipiao_xiaoxiangshuie=xiaoxiang_3huowu_weikaipiao_xiaoxiangshuie;
this.xiaoxiang_3huowu_heji_xiaoshoue=xiaoxiang_3huowu_heji_xiaoshoue;
this.xiaoxiang_3huowu_heji_xiaoxiangshuie=xiaoxiang_3huowu_heji_xiaoxiangshuie;
this.xiaoxiang_3fuwu_shuikong_xiaoshoue=xiaoxiang_3fuwu_shuikong_xiaoshoue;
this.xiaoxiang_3fuwu_shuikong_xiaoxiangshuie=xiaoxiang_3fuwu_shuikong_xiaoxiangshuie;
this.xiaoxiang_3fuwu_qita_xiaoshoue=xiaoxiang_3fuwu_qita_xiaoshoue;
this.xiaoxiang_3fuwu_qita_xiaoxiangshuie=xiaoxiang_3fuwu_qita_xiaoxiangshuie;
this.xiaoxiang_3fuwu_weikaipiao_xiaoshoue=xiaoxiang_3fuwu_weikaipiao_xiaoshoue;
this.xiaoxiang_3fuwu_weikaipiao_xiaoxiangshuie=xiaoxiang_3fuwu_weikaipiao_xiaoxiangshuie;
this.xiaoxiang_3fuwu_heji_xiaoshoue=xiaoxiang_3fuwu_heji_xiaoshoue;
this.xiaoxiang_3fuwu_heji_xiaoxiangshuie=xiaoxiang_3fuwu_heji_xiaoxiangshuie;
this.xiaoxiang_3fuwu_heji_jiashuiheji=xiaoxiang_3fuwu_heji_jiashuiheji;
this.xiaoxiang_3fuwu_kouchuhou_xiaoshoue=xiaoxiang_3fuwu_kouchuhou_xiaoshoue;
this.xiaoxiang_3fuwu_kouchuhou_xiaoxiangshuie=xiaoxiang_3fuwu_kouchuhou_xiaoxiangshuie;
this.yuzhenglv_a=yuzhenglv_a;
this.yuzhenglv_a_shuikong_xiaoshoue=yuzhenglv_a_shuikong_xiaoshoue;
this.yuzhenglv_a_shuikong_xiaoxiangshuie=yuzhenglv_a_shuikong_xiaoxiangshuie;
this.yuzhenglv_a_qita_xiaoshoue=yuzhenglv_a_qita_xiaoshoue;
this.yuzhenglv_a_qita_xiaoxiangshuie=yuzhenglv_a_qita_xiaoxiangshuie;
this.yuzhenglv_a_weikaipiao_xiaoshoue=yuzhenglv_a_weikaipiao_xiaoshoue;
this.yuzhenglv_a_weikaipiao_xiaoxiangshuie=yuzhenglv_a_weikaipiao_xiaoxiangshuie;
this.yuzhenglv_a_heji_xiaoshoue=yuzhenglv_a_heji_xiaoshoue;
this.yuzhenglv_a_heji_xiaoxiangshuie=yuzhenglv_a_heji_xiaoxiangshuie;
this.yuzhenglv_a_heji_jiashuiheji=yuzhenglv_a_heji_jiashuiheji;
this.yuzhenglv_a_shijikouchu=yuzhenglv_a_shijikouchu;
this.yuzhenglv_a_kouchuhou_xiaoshoue=yuzhenglv_a_kouchuhou_xiaoshoue;
this.yuzhenglv_a_kouchuhou_xiaoxiangshuie=yuzhenglv_a_kouchuhou_xiaoxiangshuie;
this.yuzhenglv_b_shuikong_xiaoshoue=yuzhenglv_b_shuikong_xiaoshoue;
this.yuzhenglv_b_shuikong_xiaoxiangshuie=yuzhenglv_b_shuikong_xiaoxiangshuie;
this.yuzhenglv_b_qita_xiaoshoue=yuzhenglv_b_qita_xiaoshoue;
this.yuzhenglv_b_qita_xiaoxiangshuie=yuzhenglv_b_qita_xiaoxiangshuie;
this.yuzhenglv_b_weikaipiao_xiaoshoue=yuzhenglv_b_weikaipiao_xiaoshoue;
this.yuzhenglv_b_weikaipiao_xiaoxiangshuie=yuzhenglv_b_weikaipiao_xiaoxiangshuie;
this.yuzhenglv_b_heji_xiaoshoue=yuzhenglv_b_heji_xiaoshoue;
this.yuzhenglv_b_heji_xiaoxiangshuie=yuzhenglv_b_heji_xiaoxiangshuie;
this.yuzhenglv_b_heji_jiashuiheji=yuzhenglv_b_heji_jiashuiheji;
this.yuzhenglv_b_shijikouchu=yuzhenglv_b_shijikouchu;
this.yuzhenglv_b_kouchuhou_xiaoshoue=yuzhenglv_b_kouchuhou_xiaoshoue;
this.yuzhenglv_b_kouchuhou_xiaoxiangshuie=yuzhenglv_b_kouchuhou_xiaoxiangshuie;
this.yuzhenglv_c_shuikong_xiaoshoue=yuzhenglv_c_shuikong_xiaoshoue;
this.yuzhenglv_c_shuikong_xiaoxiangshuie=yuzhenglv_c_shuikong_xiaoxiangshuie;
this.yuzhenglv_c_qita_xiaoshoue=yuzhenglv_c_qita_xiaoshoue;
this.yuzhenglv_c_qita_xiaoxiangshuie=yuzhenglv_c_qita_xiaoxiangshuie;
this.yuzhenglv_c_weikaipiao_xiaoshoue=yuzhenglv_c_weikaipiao_xiaoshoue;
this.yuzhenglv_c_weikaipiao_xiaoxiangshuie=yuzhenglv_c_weikaipiao_xiaoxiangshuie;
this.yuzhenglv_c_heji_xiaoshoue=yuzhenglv_c_heji_xiaoshoue;
this.yuzhenglv_c_heji_xiaoxiangshuie=yuzhenglv_c_heji_xiaoxiangshuie;
this.yuzhenglv_c_heji_jiashuiheji=yuzhenglv_c_heji_jiashuiheji;
this.yuzhenglv_c_shjikouchu=yuzhenglv_c_shjikouchu;
this.yuzhenglv_c_kouchuhou_xiaoshoue=yuzhenglv_c_kouchuhou_xiaoshoue;
this.yuzhenglv_c_kouchuhou_xiaoxiangshuie=yuzhenglv_c_kouchuhou_xiaoxiangshuie;
this.jianyi_jizhenghuowu_heji_xiaoshoue=jianyi_jizhenghuowu_heji_xiaoshoue;
this.jianyi_jizhenghuowu_heji_xiaoxiangshuie=jianyi_jizhenghuowu_heji_xiaoxiangshuie;
this.jianyi_jizhengfuwu_heji_xiaoshoue=jianyi_jizhengfuwu_heji_xiaoshoue;
this.jianyi_jizhengfuwu_heji_xiaoxiangshuie=jianyi_jizhengfuwu_heji_xiaoxiangshuie;
this.jianyi_jizhengfuwu_heji_jiashuiheji=jianyi_jizhengfuwu_heji_jiashuiheji;
this.jianyi_jizhengfuwu_shijikouchu=jianyi_jizhengfuwu_shijikouchu;
this.jianyi_jizhengfuwu_kouchuhou_xiaoshoue=jianyi_jizhengfuwu_kouchuhou_xiaoshoue;
this.jianyi_jizhengfuwu_kouchuhou_xiaoxiangshuie=jianyi_jizhengfuwu_kouchuhou_xiaoxiangshuie;
this.miandi_huowujiagongxiuli_qita_xiaoshoue=miandi_huowujiagongxiuli_qita_xiaoshoue;
this.miandi_huowujiagongxiuli_weikaipiao_xiushoue=miandi_huowujiagongxiuli_weikaipiao_xiushoue;
this.miandi_huowujiagongxiuli_heji_xiaoshoue=miandi_huowujiagongxiuli_heji_xiaoshoue;
this.miandi_fu_bu_wu_qita_xiaoshoue=miandi_fu_bu_wu_qita_xiaoshoue;
this.miandi_fu_bu_wu_weikaipiao_xiaoshoue=miandi_fu_bu_wu_weikaipiao_xiaoshoue;
this.miandi_fu_bu_wu_heji_xiaoshoue=miandi_fu_bu_wu_heji_xiaoshoue;
this.miandi_fu_bu_wu_heji_jiashuiheji=miandi_fu_bu_wu_heji_jiashuiheji;
this.miandi_fu_bu_wu_shijikouchu=miandi_fu_bu_wu_shijikouchu;
this.miandi_fu_bu_wu_kouchuhou_xiaoshoue=miandi_fu_bu_wu_kouchuhou_xiaoshoue;
this.mianshui_huowujiagong_shuikong_xiaoshoue=mianshui_huowujiagong_shuikong_xiaoshoue;
this.mianshui_huowujiagong_shuikong_xiaoxiangshuie=mianshui_huowujiagong_shuikong_xiaoxiangshuie;
this.mianshui_huowujiagong_qita_xiaoshuoe=mianshui_huowujiagong_qita_xiaoshuoe;
this.mianshui_huowujiagong_weikaipiao_xiaoshoue=mianshui_huowujiagong_weikaipiao_xiaoshoue;
this.mianshui_huowujiagong_heji_xiaoshoue=mianshui_huowujiagong_heji_xiaoshoue;
this.mianshui_fu_bu_wu_qita_xiaoshoue=mianshui_fu_bu_wu_qita_xiaoshoue;
this.mianshui_fu_bu_wu_weikaipiao_xiaoshoue=mianshui_fu_bu_wu_weikaipiao_xiaoshoue;
this.mianshui_fu_bu_wu_heji_xiaoshoue=mianshui_fu_bu_wu_heji_xiaoshoue;
this.mianshui_fu_bu_wu_heji_jiashuiheji=mianshui_fu_bu_wu_heji_jiashuiheji;
this.mianshui_fu_bu_wu_shijikouchu=mianshui_fu_bu_wu_shijikouchu;
this.mianshui_fu_bu_wu_kouchuhou_xiaoshoue=mianshui_fu_bu_wu_kouchuhou_xiaoshoue;
}

public void setId (Long id) {
this.id=id;
}

public Long getId () {
return this.id;
}

public void setProject_id (Long project_id) {
this.project_id=project_id;
}

public Long getProject_id () {
return this.project_id;
}

public void setXiaoxiang_17huowujiagong_shuikong_xiaoshoue (Double xiaoxiang_17huowujiagong_shuikong_xiaoshoue) {
	this.xiaoxiang_17huowujiagong_shuikong_xiaoshoue=xiaoxiang_17huowujiagong_shuikong_xiaoshoue;
}

public Double getXiaoxiang_17huowujiagong_shuikong_xiaoshoue () {
return this.xiaoxiang_17huowujiagong_shuikong_xiaoshoue;
}

public void setXiaoxiang_17huowujiagong_shukong_xiaoxiangshuie (Double xiaoxiang_17huowujiagong_shukong_xiaoxiangshuie) {
	this.xiaoxiang_17huowujiagong_shukong_xiaoxiangshuie=xiaoxiang_17huowujiagong_shukong_xiaoxiangshuie;
}

public Double getXiaoxiang_17huowujiagong_shukong_xiaoxiangshuie () {
return this.xiaoxiang_17huowujiagong_shukong_xiaoxiangshuie;
}

public void setXiaoxiang_17huowujiagong_qita_xiaoshoue (Double xiaoxiang_17huowujiagong_qita_xiaoshoue) {
	this.xiaoxiang_17huowujiagong_qita_xiaoshoue=xiaoxiang_17huowujiagong_qita_xiaoshoue;
}

public Double getXiaoxiang_17huowujiagong_qita_xiaoshoue () {
return this.xiaoxiang_17huowujiagong_qita_xiaoshoue;
}

public void setXiaoxiang_17huowujiagong_qita_xiaoxiangshuie (Double xiaoxiang_17huowujiagong_qita_xiaoxiangshuie) {
	this.xiaoxiang_17huowujiagong_qita_xiaoxiangshuie=xiaoxiang_17huowujiagong_qita_xiaoxiangshuie;
}

public Double getXiaoxiang_17huowujiagong_qita_xiaoxiangshuie () {
return this.xiaoxiang_17huowujiagong_qita_xiaoxiangshuie;
}

public void setXiaoxiang_17huowujiagong_weikaipiao_xiaoshoue (Double xiaoxiang_17huowujiagong_weikaipiao_xiaoshoue) {
	this.xiaoxiang_17huowujiagong_weikaipiao_xiaoshoue=xiaoxiang_17huowujiagong_weikaipiao_xiaoshoue;
}

public Double getXiaoxiang_17huowujiagong_weikaipiao_xiaoshoue () {
return this.xiaoxiang_17huowujiagong_weikaipiao_xiaoshoue;
}

public void setXiaoxiang_17huowujiagong_weikaipiao_xiaoxiangshuie (Double xiaoxiang_17huowujiagong_weikaipiao_xiaoxiangshuie) {
	this.xiaoxiang_17huowujiagong_weikaipiao_xiaoxiangshuie=xiaoxiang_17huowujiagong_weikaipiao_xiaoxiangshuie;
}

public Double getXiaoxiang_17huowujiagong_weikaipiao_xiaoxiangshuie () {
return this.xiaoxiang_17huowujiagong_weikaipiao_xiaoxiangshuie;
}

public void setXiaoxiang_17huowujiagong_nashui_xiaoshoue (Double xiaoxiang_17huowujiagong_nashui_xiaoshoue) {
	this.xiaoxiang_17huowujiagong_nashui_xiaoshoue=xiaoxiang_17huowujiagong_nashui_xiaoshoue;
}

public Double getXiaoxiang_17huowujiagong_nashui_xiaoshoue () {
return this.xiaoxiang_17huowujiagong_nashui_xiaoshoue;
}

public void setXiaoxiang_17huowujiagong_nashui_xiaoxiangshuie (Double xiaoxiang_17huowujiagong_nashui_xiaoxiangshuie) {
	this.xiaoxiang_17huowujiagong_nashui_xiaoxiangshuie=xiaoxiang_17huowujiagong_nashui_xiaoxiangshuie;
}

public Double getXiaoxiang_17huowujiagong_nashui_xiaoxiangshuie () {
return this.xiaoxiang_17huowujiagong_nashui_xiaoxiangshuie;
}

public void setXiaoxiang_17huowujiagong_heji_xiaoshoue (Double xiaoxiang_17huowujiagong_heji_xiaoshoue) {
	this.xiaoxiang_17huowujiagong_heji_xiaoshoue=xiaoxiang_17huowujiagong_heji_xiaoshoue;
}

public Double getXiaoxiang_17huowujiagong_heji_xiaoshoue () {
return this.xiaoxiang_17huowujiagong_heji_xiaoshoue;
}

public void setXiaoxiang_17huowujiagong_heji_xiaoxiangshuie (Double xiaoxiang_17huowujiagong_heji_xiaoxiangshuie) {
	this.xiaoxiang_17huowujiagong_heji_xiaoxiangshuie=xiaoxiang_17huowujiagong_heji_xiaoxiangshuie;
}

public Double getXiaoxiang_17huowujiagong_heji_xiaoxiangshuie () {
return this.xiaoxiang_17huowujiagong_heji_xiaoxiangshuie;
}

public void setXiaoxiang_17fuwuwuxing_shuikong_xiaoshoue (Double xiaoxiang_17fuwuwuxing_shuikong_xiaoshoue) {
	this.xiaoxiang_17fuwuwuxing_shuikong_xiaoshoue=xiaoxiang_17fuwuwuxing_shuikong_xiaoshoue;
}

public Double getXiaoxiang_17fuwuwuxing_shuikong_xiaoshoue () {
return this.xiaoxiang_17fuwuwuxing_shuikong_xiaoshoue;
}

public void setXiaoxiang_17fuwuwuxing_shuikong_xiaoxiangshuie (Double xiaoxiang_17fuwuwuxing_shuikong_xiaoxiangshuie) {
	this.xiaoxiang_17fuwuwuxing_shuikong_xiaoxiangshuie=xiaoxiang_17fuwuwuxing_shuikong_xiaoxiangshuie;
}

public Double getXiaoxiang_17fuwuwuxing_shuikong_xiaoxiangshuie () {
return this.xiaoxiang_17fuwuwuxing_shuikong_xiaoxiangshuie;
}

public void setXiaoxiang_17fuwuwuxing_qita_xiaoshoue (Double xiaoxiang_17fuwuwuxing_qita_xiaoshoue) {
	this.xiaoxiang_17fuwuwuxing_qita_xiaoshoue=xiaoxiang_17fuwuwuxing_qita_xiaoshoue;
}

public Double getXiaoxiang_17fuwuwuxing_qita_xiaoshoue () {
return this.xiaoxiang_17fuwuwuxing_qita_xiaoshoue;
}

public void setXiaoxiang_17fuwuwuxing_qita_xiaoxiangshuie (Double xiaoxiang_17fuwuwuxing_qita_xiaoxiangshuie) {
	this.xiaoxiang_17fuwuwuxing_qita_xiaoxiangshuie=xiaoxiang_17fuwuwuxing_qita_xiaoxiangshuie;
}

public Double getXiaoxiang_17fuwuwuxing_qita_xiaoxiangshuie () {
return this.xiaoxiang_17fuwuwuxing_qita_xiaoxiangshuie;
}

public void setXiaoxiang_17fuwuwuxing_weikaipiao_xiaoshoue (Double xiaoxiang_17fuwuwuxing_weikaipiao_xiaoshoue) {
	this.xiaoxiang_17fuwuwuxing_weikaipiao_xiaoshoue=xiaoxiang_17fuwuwuxing_weikaipiao_xiaoshoue;
}

public Double getXiaoxiang_17fuwuwuxing_weikaipiao_xiaoshoue () {
return this.xiaoxiang_17fuwuwuxing_weikaipiao_xiaoshoue;
}

public void setXiaoxiang_17fuwuwuxing_weikaipiao_xiaoxiangshuie (Double xiaoxiang_17fuwuwuxing_weikaipiao_xiaoxiangshuie) {
	this.xiaoxiang_17fuwuwuxing_weikaipiao_xiaoxiangshuie=xiaoxiang_17fuwuwuxing_weikaipiao_xiaoxiangshuie;
}

public Double getXiaoxiang_17fuwuwuxing_weikaipiao_xiaoxiangshuie () {
return this.xiaoxiang_17fuwuwuxing_weikaipiao_xiaoxiangshuie;
}

public void setXiaoxiang_17fuwuwuxing_nashui_xiaoshoue (Double xiaoxiang_17fuwuwuxing_nashui_xiaoshoue) {
	this.xiaoxiang_17fuwuwuxing_nashui_xiaoshoue=xiaoxiang_17fuwuwuxing_nashui_xiaoshoue;
}

public Double getXiaoxiang_17fuwuwuxing_nashui_xiaoshoue () {
return this.xiaoxiang_17fuwuwuxing_nashui_xiaoshoue;
}

public void setXiaoxiang_17fuwuwuxing_nashui_xiaoxiangshuie (Double xiaoxiang_17fuwuwuxing_nashui_xiaoxiangshuie) {
	this.xiaoxiang_17fuwuwuxing_nashui_xiaoxiangshuie=xiaoxiang_17fuwuwuxing_nashui_xiaoxiangshuie;
}

public Double getXiaoxiang_17fuwuwuxing_nashui_xiaoxiangshuie () {
return this.xiaoxiang_17fuwuwuxing_nashui_xiaoxiangshuie;
}

public void setXiaoxiang_17fuwuwuxing_heji_xiaoshoue (Double xiaoxiang_17fuwuwuxing_heji_xiaoshoue) {
	this.xiaoxiang_17fuwuwuxing_heji_xiaoshoue=xiaoxiang_17fuwuwuxing_heji_xiaoshoue;
}

public Double getXiaoxiang_17fuwuwuxing_heji_xiaoshoue () {
return this.xiaoxiang_17fuwuwuxing_heji_xiaoshoue;
}

public void setXiaoxiang_17fuwuwuxing_heji_xiaoxiangshuie (Double xiaoxiang_17fuwuwuxing_heji_xiaoxiangshuie) {
	this.xiaoxiang_17fuwuwuxing_heji_xiaoxiangshuie=xiaoxiang_17fuwuwuxing_heji_xiaoxiangshuie;
}

public Double getXiaoxiang_17fuwuwuxing_heji_xiaoxiangshuie () {
return this.xiaoxiang_17fuwuwuxing_heji_xiaoxiangshuie;
}

public void setXiaoxiang_17fuwuwuxing_heji_jiashuiheji (Double xiaoxiang_17fuwuwuxing_heji_jiashuiheji) {
	this.xiaoxiang_17fuwuwuxing_heji_jiashuiheji=xiaoxiang_17fuwuwuxing_heji_jiashuiheji;
}

public Double getXiaoxiang_17fuwuwuxing_heji_jiashuiheji () {
return this.xiaoxiang_17fuwuwuxing_heji_jiashuiheji;
}

public void setXiaoxiang_17fuwuwuxing_shijikouchu (Double xiaoxiang_17fuwuwuxing_shijikouchu) {
	this.xiaoxiang_17fuwuwuxing_shijikouchu=xiaoxiang_17fuwuwuxing_shijikouchu;
}

public Double getXiaoxiang_17fuwuwuxing_shijikouchu () {
return this.xiaoxiang_17fuwuwuxing_shijikouchu;
}

public void setXiaoxiang_17fuwuwuxing_kouchuhou_hanshuixiaoshoue (Double xiaoxiang_17fuwuwuxing_kouchuhou_hanshuixiaoshoue) {
	this.xiaoxiang_17fuwuwuxing_kouchuhou_hanshuixiaoshoue=xiaoxiang_17fuwuwuxing_kouchuhou_hanshuixiaoshoue;
}

public Double getXiaoxiang_17fuwuwuxing_kouchuhou_hanshuixiaoshoue () {
return this.xiaoxiang_17fuwuwuxing_kouchuhou_hanshuixiaoshoue;
}

public void setXiaoxiang_17fuwuwuxing_kouchuhou_xiaoxianghshuie (Double xiaoxiang_17fuwuwuxing_kouchuhou_xiaoxianghshuie) {
	this.xiaoxiang_17fuwuwuxing_kouchuhou_xiaoxianghshuie=xiaoxiang_17fuwuwuxing_kouchuhou_xiaoxianghshuie;
}

public Double getXiaoxiang_17fuwuwuxing_kouchuhou_xiaoxianghshuie () {
return this.xiaoxiang_17fuwuwuxing_kouchuhou_xiaoxianghshuie;
}

public void setXiaoxiang_13_shuikong_xiaoshoue (Double xiaoxiang_13_shuikong_xiaoshoue) {
	this.xiaoxiang_13_shuikong_xiaoshoue=xiaoxiang_13_shuikong_xiaoshoue;
}

public Double getXiaoxiang_13_shuikong_xiaoshoue () {
return this.xiaoxiang_13_shuikong_xiaoshoue;
}

public void setXiaoxiang_13_shuikong_xiaoxiangshuie (Double xiaoxiang_13_shuikong_xiaoxiangshuie) {
	this.xiaoxiang_13_shuikong_xiaoxiangshuie=xiaoxiang_13_shuikong_xiaoxiangshuie;
}

public Double getXiaoxiang_13_shuikong_xiaoxiangshuie () {
return this.xiaoxiang_13_shuikong_xiaoxiangshuie;
}

public void setXiaoxiang_13_qita_xiaoshoue (Double xiaoxiang_13_qita_xiaoshoue) {
	this.xiaoxiang_13_qita_xiaoshoue=xiaoxiang_13_qita_xiaoshoue;
}

public Double getXiaoxiang_13_qita_xiaoshoue () {
return this.xiaoxiang_13_qita_xiaoshoue;
}

public void setXiaoxiang_13_qita_xiaoxiangshuie (Double xiaoxiang_13_qita_xiaoxiangshuie) {
	this.xiaoxiang_13_qita_xiaoxiangshuie=xiaoxiang_13_qita_xiaoxiangshuie;
}

public Double getXiaoxiang_13_qita_xiaoxiangshuie () {
return this.xiaoxiang_13_qita_xiaoxiangshuie;
}

public void setXiaoxiang_13_weikaipiao_xiaoshoue (Double xiaoxiang_13_weikaipiao_xiaoshoue) {
	this.xiaoxiang_13_weikaipiao_xiaoshoue=xiaoxiang_13_weikaipiao_xiaoshoue;
}

public Double getXiaoxiang_13_weikaipiao_xiaoshoue () {
return this.xiaoxiang_13_weikaipiao_xiaoshoue;
}

public void setXiaoxiang_13_weikaipiao_xiaoxiangshuie (Double xiaoxiang_13_weikaipiao_xiaoxiangshuie) {
	this.xiaoxiang_13_weikaipiao_xiaoxiangshuie=xiaoxiang_13_weikaipiao_xiaoxiangshuie;
}

public Double getXiaoxiang_13_weikaipiao_xiaoxiangshuie () {
return this.xiaoxiang_13_weikaipiao_xiaoxiangshuie;
}

public void setXiaoxiang_13_nashui_xiaoshoue (Double xiaoxiang_13_nashui_xiaoshoue) {
	this.xiaoxiang_13_nashui_xiaoshoue=xiaoxiang_13_nashui_xiaoshoue;
}

public Double getXiaoxiang_13_nashui_xiaoshoue () {
return this.xiaoxiang_13_nashui_xiaoshoue;
}

public void setXiaoxiang_13_nashui_xiaoxiangshuie (Double xiaoxiang_13_nashui_xiaoxiangshuie) {
	this.xiaoxiang_13_nashui_xiaoxiangshuie=xiaoxiang_13_nashui_xiaoxiangshuie;
}

public Double getXiaoxiang_13_nashui_xiaoxiangshuie () {
return this.xiaoxiang_13_nashui_xiaoxiangshuie;
}

public void setXiaoxiang_13_heji_xiaoshoue (Double xiaoxiang_13_heji_xiaoshoue) {
	this.xiaoxiang_13_heji_xiaoshoue=xiaoxiang_13_heji_xiaoshoue;
}

public Double getXiaoxiang_13_heji_xiaoshoue () {
return this.xiaoxiang_13_heji_xiaoshoue;
}

public void setXiaoxiang_13_heji_xiaoxiangshuie (Double xiaoxiang_13_heji_xiaoxiangshuie) {
	this.xiaoxiang_13_heji_xiaoxiangshuie=xiaoxiang_13_heji_xiaoxiangshuie;
}

public Double getXiaoxiang_13_heji_xiaoxiangshuie () {
return this.xiaoxiang_13_heji_xiaoxiangshuie;
}

public void setXiaoxiang_11_shuikong_xiaoshoue (Double xiaoxiang_11_shuikong_xiaoshoue) {
	this.xiaoxiang_11_shuikong_xiaoshoue=xiaoxiang_11_shuikong_xiaoshoue;
}

public Double getXiaoxiang_11_shuikong_xiaoshoue () {
return this.xiaoxiang_11_shuikong_xiaoshoue;
}

public void setXiaoxiang_11_shuikong_xiaoxiangshuie (Double xiaoxiang_11_shuikong_xiaoxiangshuie) {
	this.xiaoxiang_11_shuikong_xiaoxiangshuie=xiaoxiang_11_shuikong_xiaoxiangshuie;
}

public Double getXiaoxiang_11_shuikong_xiaoxiangshuie () {
return this.xiaoxiang_11_shuikong_xiaoxiangshuie;
}

public void setXiaoxiang_11_qita_xiaoshoue (Double xiaoxiang_11_qita_xiaoshoue) {
	this.xiaoxiang_11_qita_xiaoshoue=xiaoxiang_11_qita_xiaoshoue;
}

public Double getXiaoxiang_11_qita_xiaoshoue () {
return this.xiaoxiang_11_qita_xiaoshoue;
}

public void setXiaoxiang_11_qita_xiaoxiangshuie (Double xiaoxiang_11_qita_xiaoxiangshuie) {
	this.xiaoxiang_11_qita_xiaoxiangshuie=xiaoxiang_11_qita_xiaoxiangshuie;
}

public Double getXiaoxiang_11_qita_xiaoxiangshuie () {
return this.xiaoxiang_11_qita_xiaoxiangshuie;
}

public void setXiaoxiang_11_weikaipiao_xiaoshoue (Double xiaoxiang_11_weikaipiao_xiaoshoue) {
	this.xiaoxiang_11_weikaipiao_xiaoshoue=xiaoxiang_11_weikaipiao_xiaoshoue;
}

public Double getXiaoxiang_11_weikaipiao_xiaoshoue () {
return this.xiaoxiang_11_weikaipiao_xiaoshoue;
}

public void setXiaoxiang_11_weikaipiao_xiaoxiangshuie (Double xiaoxiang_11_weikaipiao_xiaoxiangshuie) {
	this.xiaoxiang_11_weikaipiao_xiaoxiangshuie=xiaoxiang_11_weikaipiao_xiaoxiangshuie;
}

public Double getXiaoxiang_11_weikaipiao_xiaoxiangshuie () {
return this.xiaoxiang_11_weikaipiao_xiaoxiangshuie;
}

public void setXiaoxiang_11_nashui_xiaoshoue (Double xiaoxiang_11_nashui_xiaoshoue) {
	this.xiaoxiang_11_nashui_xiaoshoue=xiaoxiang_11_nashui_xiaoshoue;
}

public Double getXiaoxiang_11_nashui_xiaoshoue () {
return this.xiaoxiang_11_nashui_xiaoshoue;
}

public void setXiaoxiang_11_nashui_xiaoxiangshuie (Double xiaoxiang_11_nashui_xiaoxiangshuie) {
	this.xiaoxiang_11_nashui_xiaoxiangshuie=xiaoxiang_11_nashui_xiaoxiangshuie;
}

public Double getXiaoxiang_11_nashui_xiaoxiangshuie () {
return this.xiaoxiang_11_nashui_xiaoxiangshuie;
}

public void setXiaoxiang_11_heji_xiaoshoue (Double xiaoxiang_11_heji_xiaoshoue) {
	this.xiaoxiang_11_heji_xiaoshoue=xiaoxiang_11_heji_xiaoshoue;
}

public Double getXiaoxiang_11_heji_xiaoshoue () {
return this.xiaoxiang_11_heji_xiaoshoue;
}

public void setXiaoxiang_11_heji_xiaoxiangshuie (Double xiaoxiang_11_heji_xiaoxiangshuie) {
	this.xiaoxiang_11_heji_xiaoxiangshuie=xiaoxiang_11_heji_xiaoxiangshuie;
}

public Double getXiaoxiang_11_heji_xiaoxiangshuie () {
return this.xiaoxiang_11_heji_xiaoxiangshuie;
}

public void setXiaoxiang_11_heji_jiashuiheji (Double xiaoxiang_11_heji_jiashuiheji) {
	this.xiaoxiang_11_heji_jiashuiheji=xiaoxiang_11_heji_jiashuiheji;
}

public Double getXiaoxiang_11_heji_jiashuiheji () {
return this.xiaoxiang_11_heji_jiashuiheji;
}

public void setXiaoxiang_11_shijikouchu (Double xiaoxiang_11_shijikouchu) {
	this.xiaoxiang_11_shijikouchu=xiaoxiang_11_shijikouchu;
}

public Double getXiaoxiang_11_shijikouchu () {
return this.xiaoxiang_11_shijikouchu;
}

public void setXiaoxiang_11_kouchuhou_hanshuixiaoshoue (Double xiaoxiang_11_kouchuhou_hanshuixiaoshoue) {
	this.xiaoxiang_11_kouchuhou_hanshuixiaoshoue=xiaoxiang_11_kouchuhou_hanshuixiaoshoue;
}

public Double getXiaoxiang_11_kouchuhou_hanshuixiaoshoue () {
return this.xiaoxiang_11_kouchuhou_hanshuixiaoshoue;
}

public void setXiaoxiang_11_kouchuhou_xiaoxiangshuie (Double xiaoxiang_11_kouchuhou_xiaoxiangshuie) {
	this.xiaoxiang_11_kouchuhou_xiaoxiangshuie=xiaoxiang_11_kouchuhou_xiaoxiangshuie;
}

public Double getXiaoxiang_11_kouchuhou_xiaoxiangshuie () {
return this.xiaoxiang_11_kouchuhou_xiaoxiangshuie;
}

public void setXiaoxiang_6_shuikong_xiaoshoue (Double xiaoxiang_6_shuikong_xiaoshoue) {
	this.xiaoxiang_6_shuikong_xiaoshoue=xiaoxiang_6_shuikong_xiaoshoue;
}

public Double getXiaoxiang_6_shuikong_xiaoshoue () {
return this.xiaoxiang_6_shuikong_xiaoshoue;
}

public void setXiaoxiang_6_shuikong_xiaoxiangshuie (Double xiaoxiang_6_shuikong_xiaoxiangshuie) {
	this.xiaoxiang_6_shuikong_xiaoxiangshuie=xiaoxiang_6_shuikong_xiaoxiangshuie;
}

public Double getXiaoxiang_6_shuikong_xiaoxiangshuie () {
return this.xiaoxiang_6_shuikong_xiaoxiangshuie;
}

public void setXiaoxiang_6_qita_xiaoshoue (Double xiaoxiang_6_qita_xiaoshoue) {
	this.xiaoxiang_6_qita_xiaoshoue=xiaoxiang_6_qita_xiaoshoue;
}

public Double getXiaoxiang_6_qita_xiaoshoue () {
return this.xiaoxiang_6_qita_xiaoshoue;
}

public void setXiaoxiang_6_qita_xiaoxiangshuie (Double xiaoxiang_6_qita_xiaoxiangshuie) {
	this.xiaoxiang_6_qita_xiaoxiangshuie=xiaoxiang_6_qita_xiaoxiangshuie;
}

public Double getXiaoxiang_6_qita_xiaoxiangshuie () {
return this.xiaoxiang_6_qita_xiaoxiangshuie;
}

public void setXiaoxiang_6_weikaipiao_xiaoshoue (Double xiaoxiang_6_weikaipiao_xiaoshoue) {
	this.xiaoxiang_6_weikaipiao_xiaoshoue=xiaoxiang_6_weikaipiao_xiaoshoue;
}

public Double getXiaoxiang_6_weikaipiao_xiaoshoue () {
return this.xiaoxiang_6_weikaipiao_xiaoshoue;
}

public void setXiaoxiang_6_weikaipiao_xiaoxiangshoue (Double xiaoxiang_6_weikaipiao_xiaoxiangshoue) {
	this.xiaoxiang_6_weikaipiao_xiaoxiangshoue=xiaoxiang_6_weikaipiao_xiaoxiangshoue;
}

public Double getXiaoxiang_6_weikaipiao_xiaoxiangshoue () {
return this.xiaoxiang_6_weikaipiao_xiaoxiangshoue;
}

public void setXiaoxiang_6_nashui_xiaoshoue (Double xiaoxiang_6_nashui_xiaoshoue) {
	this.xiaoxiang_6_nashui_xiaoshoue=xiaoxiang_6_nashui_xiaoshoue;
}

public Double getXiaoxiang_6_nashui_xiaoshoue () {
return this.xiaoxiang_6_nashui_xiaoshoue;
}

public void setXiaoxiang_6_nashui_xiaoxiangshuie (Double xiaoxiang_6_nashui_xiaoxiangshuie) {
	this.xiaoxiang_6_nashui_xiaoxiangshuie=xiaoxiang_6_nashui_xiaoxiangshuie;
}

public Double getXiaoxiang_6_nashui_xiaoxiangshuie () {
return this.xiaoxiang_6_nashui_xiaoxiangshuie;
}

public void setXiaoxiang_6_heji_xiaoshoue (Double xiaoxiang_6_heji_xiaoshoue) {
	this.xiaoxiang_6_heji_xiaoshoue=xiaoxiang_6_heji_xiaoshoue;
}

public Double getXiaoxiang_6_heji_xiaoshoue () {
return this.xiaoxiang_6_heji_xiaoshoue;
}

public void setXiaoxiang_6_heji_xiaoxiangshuie (Double xiaoxiang_6_heji_xiaoxiangshuie) {
	this.xiaoxiang_6_heji_xiaoxiangshuie=xiaoxiang_6_heji_xiaoxiangshuie;
}

public Double getXiaoxiang_6_heji_xiaoxiangshuie () {
return this.xiaoxiang_6_heji_xiaoxiangshuie;
}

public void setXiaoxiang_6_heji_jiashuiheji (Double xiaoxiang_6_heji_jiashuiheji) {
	this.xiaoxiang_6_heji_jiashuiheji=xiaoxiang_6_heji_jiashuiheji;
}

public Double getXiaoxiang_6_heji_jiashuiheji () {
return this.xiaoxiang_6_heji_jiashuiheji;
}

public void setXiaoxiang_6_shijikouchu (Double xiaoxiang_6_shijikouchu) {
	this.xiaoxiang_6_shijikouchu=xiaoxiang_6_shijikouchu;
}

public Double getXiaoxiang_6_shijikouchu () {
return this.xiaoxiang_6_shijikouchu;
}

public void setXiaoxiang_6_kouchuhou_xiaoshoue (Double xiaoxiang_6_kouchuhou_xiaoshoue) {
	this.xiaoxiang_6_kouchuhou_xiaoshoue=xiaoxiang_6_kouchuhou_xiaoshoue;
}

public Double getXiaoxiang_6_kouchuhou_xiaoshoue () {
return this.xiaoxiang_6_kouchuhou_xiaoshoue;
}

public void setXiaoxiang_6_kouchuhou_xiaoxiangshoue (Double xiaoxiang_6_kouchuhou_xiaoxiangshoue) {
	this.xiaoxiang_6_kouchuhou_xiaoxiangshoue=xiaoxiang_6_kouchuhou_xiaoxiangshoue;
}

public Double getXiaoxiang_6_kouchuhou_xiaoxiangshoue () {
return this.xiaoxiang_6_kouchuhou_xiaoxiangshoue;
}

public void setYiban_jizhenghuowu_heji_xiaoshoue (Double yiban_jizhenghuowu_heji_xiaoshoue) {
	this.yiban_jizhenghuowu_heji_xiaoshoue=yiban_jizhenghuowu_heji_xiaoshoue;
}

public Double getYiban_jizhenghuowu_heji_xiaoshoue () {
return this.yiban_jizhenghuowu_heji_xiaoshoue;
}

public void setYiban_jizhenghuowu_heji_xiaoxiangshuie (Double yiban_jizhenghuowu_heji_xiaoxiangshuie) {
	this.yiban_jizhenghuowu_heji_xiaoxiangshuie=yiban_jizhenghuowu_heji_xiaoxiangshuie;
}

public Double getYiban_jizhenghuowu_heji_xiaoxiangshuie () {
return this.yiban_jizhenghuowu_heji_xiaoxiangshuie;
}

public void setYiban_jizhengfuwu_heji_xiaoshoue (Double yiban_jizhengfuwu_heji_xiaoshoue) {
	this.yiban_jizhengfuwu_heji_xiaoshoue=yiban_jizhengfuwu_heji_xiaoshoue;
}

public Double getYiban_jizhengfuwu_heji_xiaoshoue () {
return this.yiban_jizhengfuwu_heji_xiaoshoue;
}

public void setYiban_jizhengfuwu_heji_xiaoxiangshuie (Double yiban_jizhengfuwu_heji_xiaoxiangshuie) {
	this.yiban_jizhengfuwu_heji_xiaoxiangshuie=yiban_jizhengfuwu_heji_xiaoxiangshuie;
}

public Double getYiban_jizhengfuwu_heji_xiaoxiangshuie () {
return this.yiban_jizhengfuwu_heji_xiaoxiangshuie;
}

public void setYiban_jizhengfuwu_heji_jiashuiheji (Double yiban_jizhengfuwu_heji_jiashuiheji) {
	this.yiban_jizhengfuwu_heji_jiashuiheji=yiban_jizhengfuwu_heji_jiashuiheji;
}

public Double getYiban_jizhengfuwu_heji_jiashuiheji () {
return this.yiban_jizhengfuwu_heji_jiashuiheji;
}

public void setYiban_jizhengfuwu_shijikouchu (Double yiban_jizhengfuwu_shijikouchu) {
	this.yiban_jizhengfuwu_shijikouchu=yiban_jizhengfuwu_shijikouchu;
}

public Double getYiban_jizhengfuwu_shijikouchu () {
return this.yiban_jizhengfuwu_shijikouchu;
}

public void setYiban_jizhengfuwu_kouchuhou_xiaoshoue (Double yiban_jizhengfuwu_kouchuhou_xiaoshoue) {
	this.yiban_jizhengfuwu_kouchuhou_xiaoshoue=yiban_jizhengfuwu_kouchuhou_xiaoshoue;
}

public Double getYiban_jizhengfuwu_kouchuhou_xiaoshoue () {
return this.yiban_jizhengfuwu_kouchuhou_xiaoshoue;
}

public void setYiban_jizhengfuwu_kouchuhou_xiaoxiangshuie (Double yiban_jizhengfuwu_kouchuhou_xiaoxiangshuie) {
	this.yiban_jizhengfuwu_kouchuhou_xiaoxiangshuie=yiban_jizhengfuwu_kouchuhou_xiaoxiangshuie;
}

public Double getYiban_jizhengfuwu_kouchuhou_xiaoxiangshuie () {
return this.yiban_jizhengfuwu_kouchuhou_xiaoxiangshuie;
}

public void setXiaoxiang_6zhengshou_shuikong_xiaoshoue (Double xiaoxiang_6zhengshou_shuikong_xiaoshoue) {
	this.xiaoxiang_6zhengshou_shuikong_xiaoshoue=xiaoxiang_6zhengshou_shuikong_xiaoshoue;
}

public Double getXiaoxiang_6zhengshou_shuikong_xiaoshoue () {
return this.xiaoxiang_6zhengshou_shuikong_xiaoshoue;
}

public void setXiaoxiang_6zhengshou_shuikong_xiaoxiangshuie (Double xiaoxiang_6zhengshou_shuikong_xiaoxiangshuie) {
	this.xiaoxiang_6zhengshou_shuikong_xiaoxiangshuie=xiaoxiang_6zhengshou_shuikong_xiaoxiangshuie;
}

public Double getXiaoxiang_6zhengshou_shuikong_xiaoxiangshuie () {
return this.xiaoxiang_6zhengshou_shuikong_xiaoxiangshuie;
}

public void setXiaoxiang_6zhengshou_qita_xiaoshoue (Double xiaoxiang_6zhengshou_qita_xiaoshoue) {
	this.xiaoxiang_6zhengshou_qita_xiaoshoue=xiaoxiang_6zhengshou_qita_xiaoshoue;
}

public Double getXiaoxiang_6zhengshou_qita_xiaoshoue () {
return this.xiaoxiang_6zhengshou_qita_xiaoshoue;
}

public void setXiaoxiang_6zhengshou_qita_xiaoxiangshuie (Double xiaoxiang_6zhengshou_qita_xiaoxiangshuie) {
	this.xiaoxiang_6zhengshou_qita_xiaoxiangshuie=xiaoxiang_6zhengshou_qita_xiaoxiangshuie;
}

public Double getXiaoxiang_6zhengshou_qita_xiaoxiangshuie () {
return this.xiaoxiang_6zhengshou_qita_xiaoxiangshuie;
}

public void setXiaoxiang_6zhengshou_weikaipiao_xiaoshoue (Double xiaoxiang_6zhengshou_weikaipiao_xiaoshoue) {
	this.xiaoxiang_6zhengshou_weikaipiao_xiaoshoue=xiaoxiang_6zhengshou_weikaipiao_xiaoshoue;
}

public Double getXiaoxiang_6zhengshou_weikaipiao_xiaoshoue () {
return this.xiaoxiang_6zhengshou_weikaipiao_xiaoshoue;
}

public void setXiaoxiang_6zhengshou_weikaipiao_xiaoxiangshuie (Double xiaoxiang_6zhengshou_weikaipiao_xiaoxiangshuie) {
	this.xiaoxiang_6zhengshou_weikaipiao_xiaoxiangshuie=xiaoxiang_6zhengshou_weikaipiao_xiaoxiangshuie;
}

public Double getXiaoxiang_6zhengshou_weikaipiao_xiaoxiangshuie () {
return this.xiaoxiang_6zhengshou_weikaipiao_xiaoxiangshuie;
}

public void setXiaoxiang_6zhengshou_heji_xiaoshoue (Double xiaoxiang_6zhengshou_heji_xiaoshoue) {
	this.xiaoxiang_6zhengshou_heji_xiaoshoue=xiaoxiang_6zhengshou_heji_xiaoshoue;
}

public Double getXiaoxiang_6zhengshou_heji_xiaoshoue () {
return this.xiaoxiang_6zhengshou_heji_xiaoshoue;
}

public void setXiaoxiang_6zhengshou_heji_xiaoxiangshuie (Double xiaoxiang_6zhengshou_heji_xiaoxiangshuie) {
	this.xiaoxiang_6zhengshou_heji_xiaoxiangshuie=xiaoxiang_6zhengshou_heji_xiaoxiangshuie;
}

public Double getXiaoxiang_6zhengshou_heji_xiaoxiangshuie () {
return this.xiaoxiang_6zhengshou_heji_xiaoxiangshuie;
}

public void setXiaoxiang_5huowu_shuikong_xiaoshoue (Double xiaoxiang_5huowu_shuikong_xiaoshoue) {
	this.xiaoxiang_5huowu_shuikong_xiaoshoue=xiaoxiang_5huowu_shuikong_xiaoshoue;
}

public Double getXiaoxiang_5huowu_shuikong_xiaoshoue () {
return this.xiaoxiang_5huowu_shuikong_xiaoshoue;
}

public void setXiaoxiang_5huowu_shuikong_xiaoxiangshuie (Double xiaoxiang_5huowu_shuikong_xiaoxiangshuie) {
	this.xiaoxiang_5huowu_shuikong_xiaoxiangshuie=xiaoxiang_5huowu_shuikong_xiaoxiangshuie;
}

public Double getXiaoxiang_5huowu_shuikong_xiaoxiangshuie () {
return this.xiaoxiang_5huowu_shuikong_xiaoxiangshuie;
}

public void setXiaoxiang_5huowu_qita_xiaoshoue (Double xiaoxiang_5huowu_qita_xiaoshoue) {
	this.xiaoxiang_5huowu_qita_xiaoshoue=xiaoxiang_5huowu_qita_xiaoshoue;
}

public Double getXiaoxiang_5huowu_qita_xiaoshoue () {
return this.xiaoxiang_5huowu_qita_xiaoshoue;
}

public void setXiaoxiang_5huowu_qita_xiaoxiangshuie (Double xiaoxiang_5huowu_qita_xiaoxiangshuie) {
	this.xiaoxiang_5huowu_qita_xiaoxiangshuie=xiaoxiang_5huowu_qita_xiaoxiangshuie;
}

public Double getXiaoxiang_5huowu_qita_xiaoxiangshuie () {
return this.xiaoxiang_5huowu_qita_xiaoxiangshuie;
}

public void setXiaoxiang_5huowu_weikaipiao_xiaoshoue (Double xiaoxiang_5huowu_weikaipiao_xiaoshoue) {
	this.xiaoxiang_5huowu_weikaipiao_xiaoshoue=xiaoxiang_5huowu_weikaipiao_xiaoshoue;
}

public Double getXiaoxiang_5huowu_weikaipiao_xiaoshoue () {
return this.xiaoxiang_5huowu_weikaipiao_xiaoshoue;
}

public void setXiaoxiang_5huowu_weikaipiao_xiaoxiangshuie (Double xiaoxiang_5huowu_weikaipiao_xiaoxiangshuie) {
	this.xiaoxiang_5huowu_weikaipiao_xiaoxiangshuie=xiaoxiang_5huowu_weikaipiao_xiaoxiangshuie;
}

public Double getXiaoxiang_5huowu_weikaipiao_xiaoxiangshuie () {
return this.xiaoxiang_5huowu_weikaipiao_xiaoxiangshuie;
}

public void setXiaoxiang_5huowu_heji_xiaoshoue (Double xiaoxiang_5huowu_heji_xiaoshoue) {
	this.xiaoxiang_5huowu_heji_xiaoshoue=xiaoxiang_5huowu_heji_xiaoshoue;
}

public Double getXiaoxiang_5huowu_heji_xiaoshoue () {
return this.xiaoxiang_5huowu_heji_xiaoshoue;
}

public void setXiaoxiang_5huowu_heji_xiaoxiangshuie (Double xiaoxiang_5huowu_heji_xiaoxiangshuie) {
	this.xiaoxiang_5huowu_heji_xiaoxiangshuie=xiaoxiang_5huowu_heji_xiaoxiangshuie;
}

public Double getXiaoxiang_5huowu_heji_xiaoxiangshuie () {
return this.xiaoxiang_5huowu_heji_xiaoxiangshuie;
}

public void setXiaoxiang_5fuwu_shuikong_xiaoshoue (Double xiaoxiang_5fuwu_shuikong_xiaoshoue) {
	this.xiaoxiang_5fuwu_shuikong_xiaoshoue=xiaoxiang_5fuwu_shuikong_xiaoshoue;
}

public Double getXiaoxiang_5fuwu_shuikong_xiaoshoue () {
return this.xiaoxiang_5fuwu_shuikong_xiaoshoue;
}

public void setXiaoxiang_5fuwu_shuikong_xiaoxiangshuie (Double xiaoxiang_5fuwu_shuikong_xiaoxiangshuie) {
	this.xiaoxiang_5fuwu_shuikong_xiaoxiangshuie=xiaoxiang_5fuwu_shuikong_xiaoxiangshuie;
}

public Double getXiaoxiang_5fuwu_shuikong_xiaoxiangshuie () {
return this.xiaoxiang_5fuwu_shuikong_xiaoxiangshuie;
}

public void setXiaoxiang_5fuwu_qita_xiaoshoue (Double xiaoxiang_5fuwu_qita_xiaoshoue) {
	this.xiaoxiang_5fuwu_qita_xiaoshoue=xiaoxiang_5fuwu_qita_xiaoshoue;
}

public Double getXiaoxiang_5fuwu_qita_xiaoshoue () {
return this.xiaoxiang_5fuwu_qita_xiaoshoue;
}

public void setXiaoxiang_5fuwu_qita_xiaoxiangshuie (Double xiaoxiang_5fuwu_qita_xiaoxiangshuie) {
	this.xiaoxiang_5fuwu_qita_xiaoxiangshuie=xiaoxiang_5fuwu_qita_xiaoxiangshuie;
}

public Double getXiaoxiang_5fuwu_qita_xiaoxiangshuie () {
return this.xiaoxiang_5fuwu_qita_xiaoxiangshuie;
}

public void setXiaoxiang_5fuwu_weikaipiao_xiaoshoue (Double xiaoxiang_5fuwu_weikaipiao_xiaoshoue) {
	this.xiaoxiang_5fuwu_weikaipiao_xiaoshoue=xiaoxiang_5fuwu_weikaipiao_xiaoshoue;
}

public Double getXiaoxiang_5fuwu_weikaipiao_xiaoshoue () {
return this.xiaoxiang_5fuwu_weikaipiao_xiaoshoue;
}

public void setXiaoxiang_5fuwu_weikaipiao_xiaoxiangshuie (Double xiaoxiang_5fuwu_weikaipiao_xiaoxiangshuie) {
	this.xiaoxiang_5fuwu_weikaipiao_xiaoxiangshuie=xiaoxiang_5fuwu_weikaipiao_xiaoxiangshuie;
}

public Double getXiaoxiang_5fuwu_weikaipiao_xiaoxiangshuie () {
return this.xiaoxiang_5fuwu_weikaipiao_xiaoxiangshuie;
}

public void setXiaoxiang_5fuwu_heji_xiaoshoue (Double xiaoxiang_5fuwu_heji_xiaoshoue) {
	this.xiaoxiang_5fuwu_heji_xiaoshoue=xiaoxiang_5fuwu_heji_xiaoshoue;
}

public Double getXiaoxiang_5fuwu_heji_xiaoshoue () {
return this.xiaoxiang_5fuwu_heji_xiaoshoue;
}

public void setXiaoxiang_5fuwu_heji_xiaoxiangshuie (Double xiaoxiang_5fuwu_heji_xiaoxiangshuie) {
	this.xiaoxiang_5fuwu_heji_xiaoxiangshuie=xiaoxiang_5fuwu_heji_xiaoxiangshuie;
}

public Double getXiaoxiang_5fuwu_heji_xiaoxiangshuie () {
return this.xiaoxiang_5fuwu_heji_xiaoxiangshuie;
}

public void setXiaoxiang_5fuwu_heji_jiashuiheji (Double xiaoxiang_5fuwu_heji_jiashuiheji) {
	this.xiaoxiang_5fuwu_heji_jiashuiheji=xiaoxiang_5fuwu_heji_jiashuiheji;
}

public Double getXiaoxiang_5fuwu_heji_jiashuiheji () {
return this.xiaoxiang_5fuwu_heji_jiashuiheji;
}

public void setXiaoxiang_5fuwu_shijikouchu (Double xiaoxiang_5fuwu_shijikouchu) {
	this.xiaoxiang_5fuwu_shijikouchu=xiaoxiang_5fuwu_shijikouchu;
}

public Double getXiaoxiang_5fuwu_shijikouchu () {
return this.xiaoxiang_5fuwu_shijikouchu;
}

public void setXiaoxiang_5fuwu_kouchuhou_xiaoshoue (Double xiaoxiang_5fuwu_kouchuhou_xiaoshoue) {
	this.xiaoxiang_5fuwu_kouchuhou_xiaoshoue=xiaoxiang_5fuwu_kouchuhou_xiaoshoue;
}

public Double getXiaoxiang_5fuwu_kouchuhou_xiaoshoue () {
return this.xiaoxiang_5fuwu_kouchuhou_xiaoshoue;
}

public void setXiaoxiang_5fuwu_kouchuhou_xiaoxiangshuie (Double xiaoxiang_5fuwu_kouchuhou_xiaoxiangshuie) {
	this.xiaoxiang_5fuwu_kouchuhou_xiaoxiangshuie=xiaoxiang_5fuwu_kouchuhou_xiaoxiangshuie;
}

public Double getXiaoxiang_5fuwu_kouchuhou_xiaoxiangshuie () {
return this.xiaoxiang_5fuwu_kouchuhou_xiaoxiangshuie;
}

public void setXiaoxiang_4_shuikong_xiaoshoue (Double xiaoxiang_4_shuikong_xiaoshoue) {
	this.xiaoxiang_4_shuikong_xiaoshoue=xiaoxiang_4_shuikong_xiaoshoue;
}

public Double getXiaoxiang_4_shuikong_xiaoshoue () {
return this.xiaoxiang_4_shuikong_xiaoshoue;
}

public void setXiaoxiang_4_shuikong_xiaoxiangshuie (Double xiaoxiang_4_shuikong_xiaoxiangshuie) {
	this.xiaoxiang_4_shuikong_xiaoxiangshuie=xiaoxiang_4_shuikong_xiaoxiangshuie;
}

public Double getXiaoxiang_4_shuikong_xiaoxiangshuie () {
return this.xiaoxiang_4_shuikong_xiaoxiangshuie;
}

public void setXiaoxiang_4_qita_xiaoshoue (Double xiaoxiang_4_qita_xiaoshoue) {
	this.xiaoxiang_4_qita_xiaoshoue=xiaoxiang_4_qita_xiaoshoue;
}

public Double getXiaoxiang_4_qita_xiaoshoue () {
return this.xiaoxiang_4_qita_xiaoshoue;
}

public void setXiaoxiang_4_qita_xiaoxiangshuie (Double xiaoxiang_4_qita_xiaoxiangshuie) {
	this.xiaoxiang_4_qita_xiaoxiangshuie=xiaoxiang_4_qita_xiaoxiangshuie;
}

public Double getXiaoxiang_4_qita_xiaoxiangshuie () {
return this.xiaoxiang_4_qita_xiaoxiangshuie;
}

public void setXiaoxiang_4_weikaipiao_xiaoshoue (Double xiaoxiang_4_weikaipiao_xiaoshoue) {
	this.xiaoxiang_4_weikaipiao_xiaoshoue=xiaoxiang_4_weikaipiao_xiaoshoue;
}

public Double getXiaoxiang_4_weikaipiao_xiaoshoue () {
return this.xiaoxiang_4_weikaipiao_xiaoshoue;
}

public void setXiaoxiang_4_weikaipiao_xiaoxiangshuie (Double xiaoxiang_4_weikaipiao_xiaoxiangshuie) {
	this.xiaoxiang_4_weikaipiao_xiaoxiangshuie=xiaoxiang_4_weikaipiao_xiaoxiangshuie;
}

public Double getXiaoxiang_4_weikaipiao_xiaoxiangshuie () {
return this.xiaoxiang_4_weikaipiao_xiaoxiangshuie;
}

public void setXiaoxiang_4_heji_xiaoshoue (Double xiaoxiang_4_heji_xiaoshoue) {
	this.xiaoxiang_4_heji_xiaoshoue=xiaoxiang_4_heji_xiaoshoue;
}

public Double getXiaoxiang_4_heji_xiaoshoue () {
return this.xiaoxiang_4_heji_xiaoshoue;
}

public void setXiaoxiang_4_heji_xiaoxiangshuie (Double xiaoxiang_4_heji_xiaoxiangshuie) {
	this.xiaoxiang_4_heji_xiaoxiangshuie=xiaoxiang_4_heji_xiaoxiangshuie;
}

public Double getXiaoxiang_4_heji_xiaoxiangshuie () {
return this.xiaoxiang_4_heji_xiaoxiangshuie;
}

public void setXiaoxiang_3huowu_shuikong_xiaoshoue (Double xiaoxiang_3huowu_shuikong_xiaoshoue) {
	this.xiaoxiang_3huowu_shuikong_xiaoshoue=xiaoxiang_3huowu_shuikong_xiaoshoue;
}

public Double getXiaoxiang_3huowu_shuikong_xiaoshoue () {
return this.xiaoxiang_3huowu_shuikong_xiaoshoue;
}

public void setXiaoxiang_3huowu_shuikong_xiaoxiangshuie (Double xiaoxiang_3huowu_shuikong_xiaoxiangshuie) {
	this.xiaoxiang_3huowu_shuikong_xiaoxiangshuie=xiaoxiang_3huowu_shuikong_xiaoxiangshuie;
}

public Double getXiaoxiang_3huowu_shuikong_xiaoxiangshuie () {
return this.xiaoxiang_3huowu_shuikong_xiaoxiangshuie;
}

public void setXiaoxiang_3huowu_qita_xiaoshoue (Double xiaoxiang_3huowu_qita_xiaoshoue) {
	this.xiaoxiang_3huowu_qita_xiaoshoue=xiaoxiang_3huowu_qita_xiaoshoue;
}

public Double getXiaoxiang_3huowu_qita_xiaoshoue () {
return this.xiaoxiang_3huowu_qita_xiaoshoue;
}

public void setXiaoxiang_3huowu_qita_xiaoxiangshuie (Double xiaoxiang_3huowu_qita_xiaoxiangshuie) {
	this.xiaoxiang_3huowu_qita_xiaoxiangshuie=xiaoxiang_3huowu_qita_xiaoxiangshuie;
}

public Double getXiaoxiang_3huowu_qita_xiaoxiangshuie () {
return this.xiaoxiang_3huowu_qita_xiaoxiangshuie;
}

public void setXiaoxiang_3huowu_weikaipiao_xiaoshoue (Double xiaoxiang_3huowu_weikaipiao_xiaoshoue) {
	this.xiaoxiang_3huowu_weikaipiao_xiaoshoue=xiaoxiang_3huowu_weikaipiao_xiaoshoue;
}

public Double getXiaoxiang_3huowu_weikaipiao_xiaoshoue () {
return this.xiaoxiang_3huowu_weikaipiao_xiaoshoue;
}

public void setXiaoxiang_3huowu_weikaipiao_xiaoxiangshuie (Double xiaoxiang_3huowu_weikaipiao_xiaoxiangshuie) {
	this.xiaoxiang_3huowu_weikaipiao_xiaoxiangshuie=xiaoxiang_3huowu_weikaipiao_xiaoxiangshuie;
}

public Double getXiaoxiang_3huowu_weikaipiao_xiaoxiangshuie () {
return this.xiaoxiang_3huowu_weikaipiao_xiaoxiangshuie;
}

public void setXiaoxiang_3huowu_heji_xiaoshoue (Double xiaoxiang_3huowu_heji_xiaoshoue) {
	this.xiaoxiang_3huowu_heji_xiaoshoue=xiaoxiang_3huowu_heji_xiaoshoue;
}

public Double getXiaoxiang_3huowu_heji_xiaoshoue () {
return this.xiaoxiang_3huowu_heji_xiaoshoue;
}

public void setXiaoxiang_3huowu_heji_xiaoxiangshuie (Double xiaoxiang_3huowu_heji_xiaoxiangshuie) {
	this.xiaoxiang_3huowu_heji_xiaoxiangshuie=xiaoxiang_3huowu_heji_xiaoxiangshuie;
}

public Double getXiaoxiang_3huowu_heji_xiaoxiangshuie () {
return this.xiaoxiang_3huowu_heji_xiaoxiangshuie;
}

public void setXiaoxiang_3fuwu_shuikong_xiaoshoue (Double xiaoxiang_3fuwu_shuikong_xiaoshoue) {
	this.xiaoxiang_3fuwu_shuikong_xiaoshoue=xiaoxiang_3fuwu_shuikong_xiaoshoue;
}

public Double getXiaoxiang_3fuwu_shuikong_xiaoshoue () {
return this.xiaoxiang_3fuwu_shuikong_xiaoshoue;
}

public void setXiaoxiang_3fuwu_shuikong_xiaoxiangshuie (Double xiaoxiang_3fuwu_shuikong_xiaoxiangshuie) {
	this.xiaoxiang_3fuwu_shuikong_xiaoxiangshuie=xiaoxiang_3fuwu_shuikong_xiaoxiangshuie;
}

public Double getXiaoxiang_3fuwu_shuikong_xiaoxiangshuie () {
return this.xiaoxiang_3fuwu_shuikong_xiaoxiangshuie;
}

public void setXiaoxiang_3fuwu_qita_xiaoshoue (Double xiaoxiang_3fuwu_qita_xiaoshoue) {
	this.xiaoxiang_3fuwu_qita_xiaoshoue=xiaoxiang_3fuwu_qita_xiaoshoue;
}

public Double getXiaoxiang_3fuwu_qita_xiaoshoue () {
return this.xiaoxiang_3fuwu_qita_xiaoshoue;
}

public void setXiaoxiang_3fuwu_qita_xiaoxiangshuie (Double xiaoxiang_3fuwu_qita_xiaoxiangshuie) {
	this.xiaoxiang_3fuwu_qita_xiaoxiangshuie=xiaoxiang_3fuwu_qita_xiaoxiangshuie;
}

public Double getXiaoxiang_3fuwu_qita_xiaoxiangshuie () {
return this.xiaoxiang_3fuwu_qita_xiaoxiangshuie;
}

public void setXiaoxiang_3fuwu_weikaipiao_xiaoshoue (Double xiaoxiang_3fuwu_weikaipiao_xiaoshoue) {
	this.xiaoxiang_3fuwu_weikaipiao_xiaoshoue=xiaoxiang_3fuwu_weikaipiao_xiaoshoue;
}

public Double getXiaoxiang_3fuwu_weikaipiao_xiaoshoue () {
return this.xiaoxiang_3fuwu_weikaipiao_xiaoshoue;
}

public void setXiaoxiang_3fuwu_weikaipiao_xiaoxiangshuie (Double xiaoxiang_3fuwu_weikaipiao_xiaoxiangshuie) {
	this.xiaoxiang_3fuwu_weikaipiao_xiaoxiangshuie=xiaoxiang_3fuwu_weikaipiao_xiaoxiangshuie;
}

public Double getXiaoxiang_3fuwu_weikaipiao_xiaoxiangshuie () {
return this.xiaoxiang_3fuwu_weikaipiao_xiaoxiangshuie;
}

public void setXiaoxiang_3fuwu_heji_xiaoshoue (Double xiaoxiang_3fuwu_heji_xiaoshoue) {
	this.xiaoxiang_3fuwu_heji_xiaoshoue=xiaoxiang_3fuwu_heji_xiaoshoue;
}

public Double getXiaoxiang_3fuwu_heji_xiaoshoue () {
return this.xiaoxiang_3fuwu_heji_xiaoshoue;
}

public void setXiaoxiang_3fuwu_heji_xiaoxiangshuie (Double xiaoxiang_3fuwu_heji_xiaoxiangshuie) {
	this.xiaoxiang_3fuwu_heji_xiaoxiangshuie=xiaoxiang_3fuwu_heji_xiaoxiangshuie;
}

public Double getXiaoxiang_3fuwu_heji_xiaoxiangshuie () {
return this.xiaoxiang_3fuwu_heji_xiaoxiangshuie;
}

public void setXiaoxiang_3fuwu_heji_jiashuiheji (Double xiaoxiang_3fuwu_heji_jiashuiheji) {
	this.xiaoxiang_3fuwu_heji_jiashuiheji=xiaoxiang_3fuwu_heji_jiashuiheji;
}

public Double getXiaoxiang_3fuwu_heji_jiashuiheji () {
return this.xiaoxiang_3fuwu_heji_jiashuiheji;
}

public void setXiaoxiang_3fuwu_kouchuhou_xiaoshoue (Double xiaoxiang_3fuwu_kouchuhou_xiaoshoue) {
	this.xiaoxiang_3fuwu_kouchuhou_xiaoshoue=xiaoxiang_3fuwu_kouchuhou_xiaoshoue;
}

public Double getXiaoxiang_3fuwu_kouchuhou_xiaoshoue () {
return this.xiaoxiang_3fuwu_kouchuhou_xiaoshoue;
}

public void setXiaoxiang_3fuwu_kouchuhou_xiaoxiangshuie (Double xiaoxiang_3fuwu_kouchuhou_xiaoxiangshuie) {
	this.xiaoxiang_3fuwu_kouchuhou_xiaoxiangshuie=xiaoxiang_3fuwu_kouchuhou_xiaoxiangshuie;
}

public Double getXiaoxiang_3fuwu_kouchuhou_xiaoxiangshuie () {
return this.xiaoxiang_3fuwu_kouchuhou_xiaoxiangshuie;
}

public void setYuzhenglv_a (Double yuzhenglv_a) {
	this.yuzhenglv_a=yuzhenglv_a;
}

public Double getYuzhenglv_a () {
return this.yuzhenglv_a;
}

public void setYuzhenglv_a_shuikong_xiaoshoue (Double yuzhenglv_a_shuikong_xiaoshoue) {
	this.yuzhenglv_a_shuikong_xiaoshoue=yuzhenglv_a_shuikong_xiaoshoue;
}

public Double getYuzhenglv_a_shuikong_xiaoshoue () {
return this.yuzhenglv_a_shuikong_xiaoshoue;
}

public void setYuzhenglv_a_shuikong_xiaoxiangshuie (Double yuzhenglv_a_shuikong_xiaoxiangshuie) {
	this.yuzhenglv_a_shuikong_xiaoxiangshuie=yuzhenglv_a_shuikong_xiaoxiangshuie;
}

public Double getYuzhenglv_a_shuikong_xiaoxiangshuie () {
return this.yuzhenglv_a_shuikong_xiaoxiangshuie;
}

public void setYuzhenglv_a_qita_xiaoshoue (Double yuzhenglv_a_qita_xiaoshoue) {
	this.yuzhenglv_a_qita_xiaoshoue=yuzhenglv_a_qita_xiaoshoue;
}

public Double getYuzhenglv_a_qita_xiaoshoue () {
return this.yuzhenglv_a_qita_xiaoshoue;
}

public void setYuzhenglv_a_qita_xiaoxiangshuie (Double yuzhenglv_a_qita_xiaoxiangshuie) {
	this.yuzhenglv_a_qita_xiaoxiangshuie=yuzhenglv_a_qita_xiaoxiangshuie;
}

public Double getYuzhenglv_a_qita_xiaoxiangshuie () {
return this.yuzhenglv_a_qita_xiaoxiangshuie;
}

public void setYuzhenglv_a_weikaipiao_xiaoshoue (Double yuzhenglv_a_weikaipiao_xiaoshoue) {
	this.yuzhenglv_a_weikaipiao_xiaoshoue=yuzhenglv_a_weikaipiao_xiaoshoue;
}

public Double getYuzhenglv_a_weikaipiao_xiaoshoue () {
return this.yuzhenglv_a_weikaipiao_xiaoshoue;
}

public void setYuzhenglv_a_weikaipiao_xiaoxiangshuie (Double yuzhenglv_a_weikaipiao_xiaoxiangshuie) {
	this.yuzhenglv_a_weikaipiao_xiaoxiangshuie=yuzhenglv_a_weikaipiao_xiaoxiangshuie;
}

public Double getYuzhenglv_a_weikaipiao_xiaoxiangshuie () {
return this.yuzhenglv_a_weikaipiao_xiaoxiangshuie;
}

public void setYuzhenglv_a_heji_xiaoshoue (Double yuzhenglv_a_heji_xiaoshoue) {
	this.yuzhenglv_a_heji_xiaoshoue=yuzhenglv_a_heji_xiaoshoue;
}

public Double getYuzhenglv_a_heji_xiaoshoue () {
return this.yuzhenglv_a_heji_xiaoshoue;
}

public void setYuzhenglv_a_heji_xiaoxiangshuie (Double yuzhenglv_a_heji_xiaoxiangshuie) {
	this.yuzhenglv_a_heji_xiaoxiangshuie=yuzhenglv_a_heji_xiaoxiangshuie;
}

public Double getYuzhenglv_a_heji_xiaoxiangshuie () {
return this.yuzhenglv_a_heji_xiaoxiangshuie;
}

public void setYuzhenglv_a_heji_jiashuiheji (Double yuzhenglv_a_heji_jiashuiheji) {
	this.yuzhenglv_a_heji_jiashuiheji=yuzhenglv_a_heji_jiashuiheji;
}

public Double getYuzhenglv_a_heji_jiashuiheji () {
return this.yuzhenglv_a_heji_jiashuiheji;
}

public void setYuzhenglv_a_shijikouchu (Double yuzhenglv_a_shijikouchu) {
	this.yuzhenglv_a_shijikouchu=yuzhenglv_a_shijikouchu;
}

public Double getYuzhenglv_a_shijikouchu () {
return this.yuzhenglv_a_shijikouchu;
}

public void setYuzhenglv_a_kouchuhou_xiaoshoue (Double yuzhenglv_a_kouchuhou_xiaoshoue) {
	this.yuzhenglv_a_kouchuhou_xiaoshoue=yuzhenglv_a_kouchuhou_xiaoshoue;
}

public Double getYuzhenglv_a_kouchuhou_xiaoshoue () {
return this.yuzhenglv_a_kouchuhou_xiaoshoue;
}

public void setYuzhenglv_a_kouchuhou_xiaoxiangshuie (Double yuzhenglv_a_kouchuhou_xiaoxiangshuie) {
	this.yuzhenglv_a_kouchuhou_xiaoxiangshuie=yuzhenglv_a_kouchuhou_xiaoxiangshuie;
}

public Double getYuzhenglv_a_kouchuhou_xiaoxiangshuie () {
return this.yuzhenglv_a_kouchuhou_xiaoxiangshuie;
}

public void setYuzhenglv_b_shuikong_xiaoshoue (Double yuzhenglv_b_shuikong_xiaoshoue) {
	this.yuzhenglv_b_shuikong_xiaoshoue=yuzhenglv_b_shuikong_xiaoshoue;
}

public Double getYuzhenglv_b_shuikong_xiaoshoue () {
return this.yuzhenglv_b_shuikong_xiaoshoue;
}

public void setYuzhenglv_b_shuikong_xiaoxiangshuie (Double yuzhenglv_b_shuikong_xiaoxiangshuie) {
	this.yuzhenglv_b_shuikong_xiaoxiangshuie=yuzhenglv_b_shuikong_xiaoxiangshuie;
}

public Double getYuzhenglv_b_shuikong_xiaoxiangshuie () {
return this.yuzhenglv_b_shuikong_xiaoxiangshuie;
}

public void setYuzhenglv_b_qita_xiaoshoue (Double yuzhenglv_b_qita_xiaoshoue) {
	this.yuzhenglv_b_qita_xiaoshoue=yuzhenglv_b_qita_xiaoshoue;
}

public Double getYuzhenglv_b_qita_xiaoshoue () {
return this.yuzhenglv_b_qita_xiaoshoue;
}

public void setYuzhenglv_b_qita_xiaoxiangshuie (Double yuzhenglv_b_qita_xiaoxiangshuie) {
	this.yuzhenglv_b_qita_xiaoxiangshuie=yuzhenglv_b_qita_xiaoxiangshuie;
}

public Double getYuzhenglv_b_qita_xiaoxiangshuie () {
return this.yuzhenglv_b_qita_xiaoxiangshuie;
}

public void setYuzhenglv_b_weikaipiao_xiaoshoue (Double yuzhenglv_b_weikaipiao_xiaoshoue) {
	this.yuzhenglv_b_weikaipiao_xiaoshoue=yuzhenglv_b_weikaipiao_xiaoshoue;
}

public Double getYuzhenglv_b_weikaipiao_xiaoshoue () {
return this.yuzhenglv_b_weikaipiao_xiaoshoue;
}

public void setYuzhenglv_b_weikaipiao_xiaoxiangshuie (Double yuzhenglv_b_weikaipiao_xiaoxiangshuie) {
	this.yuzhenglv_b_weikaipiao_xiaoxiangshuie=yuzhenglv_b_weikaipiao_xiaoxiangshuie;
}

public Double getYuzhenglv_b_weikaipiao_xiaoxiangshuie () {
return this.yuzhenglv_b_weikaipiao_xiaoxiangshuie;
}

public void setYuzhenglv_b_heji_xiaoshoue (Double yuzhenglv_b_heji_xiaoshoue) {
	this.yuzhenglv_b_heji_xiaoshoue=yuzhenglv_b_heji_xiaoshoue;
}

public Double getYuzhenglv_b_heji_xiaoshoue () {
return this.yuzhenglv_b_heji_xiaoshoue;
}

public void setYuzhenglv_b_heji_xiaoxiangshuie (Double yuzhenglv_b_heji_xiaoxiangshuie) {
	this.yuzhenglv_b_heji_xiaoxiangshuie=yuzhenglv_b_heji_xiaoxiangshuie;
}

public Double getYuzhenglv_b_heji_xiaoxiangshuie () {
return this.yuzhenglv_b_heji_xiaoxiangshuie;
}

public void setYuzhenglv_b_heji_jiashuiheji (Double yuzhenglv_b_heji_jiashuiheji) {
	this.yuzhenglv_b_heji_jiashuiheji=yuzhenglv_b_heji_jiashuiheji;
}

public Double getYuzhenglv_b_heji_jiashuiheji () {
return this.yuzhenglv_b_heji_jiashuiheji;
}

public void setYuzhenglv_b_shijikouchu (Double yuzhenglv_b_shijikouchu) {
	this.yuzhenglv_b_shijikouchu=yuzhenglv_b_shijikouchu;
}

public Double getYuzhenglv_b_shijikouchu () {
return this.yuzhenglv_b_shijikouchu;
}

public void setYuzhenglv_b_kouchuhou_xiaoshoue (Double yuzhenglv_b_kouchuhou_xiaoshoue) {
	this.yuzhenglv_b_kouchuhou_xiaoshoue=yuzhenglv_b_kouchuhou_xiaoshoue;
}

public Double getYuzhenglv_b_kouchuhou_xiaoshoue () {
return this.yuzhenglv_b_kouchuhou_xiaoshoue;
}

public void setYuzhenglv_b_kouchuhou_xiaoxiangshuie (Double yuzhenglv_b_kouchuhou_xiaoxiangshuie) {
	this.yuzhenglv_b_kouchuhou_xiaoxiangshuie=yuzhenglv_b_kouchuhou_xiaoxiangshuie;
}

public Double getYuzhenglv_b_kouchuhou_xiaoxiangshuie () {
return this.yuzhenglv_b_kouchuhou_xiaoxiangshuie;
}

public void setYuzhenglv_c_shuikong_xiaoshoue (Double yuzhenglv_c_shuikong_xiaoshoue) {
	this.yuzhenglv_c_shuikong_xiaoshoue=yuzhenglv_c_shuikong_xiaoshoue;
}

public Double getYuzhenglv_c_shuikong_xiaoshoue () {
return this.yuzhenglv_c_shuikong_xiaoshoue;
}

public void setYuzhenglv_c_shuikong_xiaoxiangshuie (Double yuzhenglv_c_shuikong_xiaoxiangshuie) {
	this.yuzhenglv_c_shuikong_xiaoxiangshuie=yuzhenglv_c_shuikong_xiaoxiangshuie;
}

public Double getYuzhenglv_c_shuikong_xiaoxiangshuie () {
return this.yuzhenglv_c_shuikong_xiaoxiangshuie;
}

public void setYuzhenglv_c_qita_xiaoshoue (Double yuzhenglv_c_qita_xiaoshoue) {
	this.yuzhenglv_c_qita_xiaoshoue=yuzhenglv_c_qita_xiaoshoue;
}

public Double getYuzhenglv_c_qita_xiaoshoue () {
return this.yuzhenglv_c_qita_xiaoshoue;
}

public void setYuzhenglv_c_qita_xiaoxiangshuie (Double yuzhenglv_c_qita_xiaoxiangshuie) {
	this.yuzhenglv_c_qita_xiaoxiangshuie=yuzhenglv_c_qita_xiaoxiangshuie;
}

public Double getYuzhenglv_c_qita_xiaoxiangshuie () {
return this.yuzhenglv_c_qita_xiaoxiangshuie;
}

public void setYuzhenglv_c_weikaipiao_xiaoshoue (Double yuzhenglv_c_weikaipiao_xiaoshoue) {
	this.yuzhenglv_c_weikaipiao_xiaoshoue=yuzhenglv_c_weikaipiao_xiaoshoue;
}

public Double getYuzhenglv_c_weikaipiao_xiaoshoue () {
return this.yuzhenglv_c_weikaipiao_xiaoshoue;
}

public void setYuzhenglv_c_weikaipiao_xiaoxiangshuie (Double yuzhenglv_c_weikaipiao_xiaoxiangshuie) {
	this.yuzhenglv_c_weikaipiao_xiaoxiangshuie=yuzhenglv_c_weikaipiao_xiaoxiangshuie;
}

public Double getYuzhenglv_c_weikaipiao_xiaoxiangshuie () {
return this.yuzhenglv_c_weikaipiao_xiaoxiangshuie;
}

public void setYuzhenglv_c_heji_xiaoshoue (Double yuzhenglv_c_heji_xiaoshoue) {
	this.yuzhenglv_c_heji_xiaoshoue=yuzhenglv_c_heji_xiaoshoue;
}

public Double getYuzhenglv_c_heji_xiaoshoue () {
return this.yuzhenglv_c_heji_xiaoshoue;
}

public void setYuzhenglv_c_heji_xiaoxiangshuie (Double yuzhenglv_c_heji_xiaoxiangshuie) {
	this.yuzhenglv_c_heji_xiaoxiangshuie=yuzhenglv_c_heji_xiaoxiangshuie;
}

public Double getYuzhenglv_c_heji_xiaoxiangshuie () {
return this.yuzhenglv_c_heji_xiaoxiangshuie;
}

public void setYuzhenglv_c_heji_jiashuiheji (Double yuzhenglv_c_heji_jiashuiheji) {
	this.yuzhenglv_c_heji_jiashuiheji=yuzhenglv_c_heji_jiashuiheji;
}

public Double getYuzhenglv_c_heji_jiashuiheji () {
return this.yuzhenglv_c_heji_jiashuiheji;
}

public void setYuzhenglv_c_shjikouchu (Double yuzhenglv_c_shjikouchu) {
	this.yuzhenglv_c_shjikouchu=yuzhenglv_c_shjikouchu;
}

public Double getYuzhenglv_c_shjikouchu () {
return this.yuzhenglv_c_shjikouchu;
}

public void setYuzhenglv_c_kouchuhou_xiaoshoue (Double yuzhenglv_c_kouchuhou_xiaoshoue) {
	this.yuzhenglv_c_kouchuhou_xiaoshoue=yuzhenglv_c_kouchuhou_xiaoshoue;
}

public Double getYuzhenglv_c_kouchuhou_xiaoshoue () {
return this.yuzhenglv_c_kouchuhou_xiaoshoue;
}

public void setYuzhenglv_c_kouchuhou_xiaoxiangshuie (Double yuzhenglv_c_kouchuhou_xiaoxiangshuie) {
	this.yuzhenglv_c_kouchuhou_xiaoxiangshuie=yuzhenglv_c_kouchuhou_xiaoxiangshuie;
}

public Double getYuzhenglv_c_kouchuhou_xiaoxiangshuie () {
return this.yuzhenglv_c_kouchuhou_xiaoxiangshuie;
}

public void setJianyi_jizhenghuowu_heji_xiaoshoue (Double jianyi_jizhenghuowu_heji_xiaoshoue) {
	this.jianyi_jizhenghuowu_heji_xiaoshoue=jianyi_jizhenghuowu_heji_xiaoshoue;
}

public Double getJianyi_jizhenghuowu_heji_xiaoshoue () {
return this.jianyi_jizhenghuowu_heji_xiaoshoue;
}

public void setJianyi_jizhenghuowu_heji_xiaoxiangshuie (Double jianyi_jizhenghuowu_heji_xiaoxiangshuie) {
	this.jianyi_jizhenghuowu_heji_xiaoxiangshuie=jianyi_jizhenghuowu_heji_xiaoxiangshuie;
}

public Double getJianyi_jizhenghuowu_heji_xiaoxiangshuie () {
return this.jianyi_jizhenghuowu_heji_xiaoxiangshuie;
}

public void setJianyi_jizhengfuwu_heji_xiaoshoue (Double jianyi_jizhengfuwu_heji_xiaoshoue) {
	this.jianyi_jizhengfuwu_heji_xiaoshoue=jianyi_jizhengfuwu_heji_xiaoshoue;
}

public Double getJianyi_jizhengfuwu_heji_xiaoshoue () {
return this.jianyi_jizhengfuwu_heji_xiaoshoue;
}

public void setJianyi_jizhengfuwu_heji_xiaoxiangshuie (Double jianyi_jizhengfuwu_heji_xiaoxiangshuie) {
	this.jianyi_jizhengfuwu_heji_xiaoxiangshuie=jianyi_jizhengfuwu_heji_xiaoxiangshuie;
}

public Double getJianyi_jizhengfuwu_heji_xiaoxiangshuie () {
return this.jianyi_jizhengfuwu_heji_xiaoxiangshuie;
}

public void setJianyi_jizhengfuwu_heji_jiashuiheji (Double jianyi_jizhengfuwu_heji_jiashuiheji) {
	this.jianyi_jizhengfuwu_heji_jiashuiheji=jianyi_jizhengfuwu_heji_jiashuiheji;
}

public Double getJianyi_jizhengfuwu_heji_jiashuiheji () {
return this.jianyi_jizhengfuwu_heji_jiashuiheji;
}

public void setJianyi_jizhengfuwu_shijikouchu (Double jianyi_jizhengfuwu_shijikouchu) {
	this.jianyi_jizhengfuwu_shijikouchu=jianyi_jizhengfuwu_shijikouchu;
}

public Double getJianyi_jizhengfuwu_shijikouchu () {
return this.jianyi_jizhengfuwu_shijikouchu;
}

public void setJianyi_jizhengfuwu_kouchuhou_xiaoshoue (Double jianyi_jizhengfuwu_kouchuhou_xiaoshoue) {
	this.jianyi_jizhengfuwu_kouchuhou_xiaoshoue=jianyi_jizhengfuwu_kouchuhou_xiaoshoue;
}

public Double getJianyi_jizhengfuwu_kouchuhou_xiaoshoue () {
return this.jianyi_jizhengfuwu_kouchuhou_xiaoshoue;
}

public void setJianyi_jizhengfuwu_kouchuhou_xiaoxiangshuie (Double jianyi_jizhengfuwu_kouchuhou_xiaoxiangshuie) {
	this.jianyi_jizhengfuwu_kouchuhou_xiaoxiangshuie=jianyi_jizhengfuwu_kouchuhou_xiaoxiangshuie;
}

public Double getJianyi_jizhengfuwu_kouchuhou_xiaoxiangshuie () {
return this.jianyi_jizhengfuwu_kouchuhou_xiaoxiangshuie;
}

public void setMiandi_huowujiagongxiuli_qita_xiaoshoue (Double miandi_huowujiagongxiuli_qita_xiaoshoue) {
	this.miandi_huowujiagongxiuli_qita_xiaoshoue=miandi_huowujiagongxiuli_qita_xiaoshoue;
}

public Double getMiandi_huowujiagongxiuli_qita_xiaoshoue () {
return this.miandi_huowujiagongxiuli_qita_xiaoshoue;
}

public void setMiandi_huowujiagongxiuli_weikaipiao_xiushoue (Double miandi_huowujiagongxiuli_weikaipiao_xiushoue) {
	this.miandi_huowujiagongxiuli_weikaipiao_xiushoue=miandi_huowujiagongxiuli_weikaipiao_xiushoue;
}

public Double getMiandi_huowujiagongxiuli_weikaipiao_xiushoue () {
return this.miandi_huowujiagongxiuli_weikaipiao_xiushoue;
}

public void setMiandi_huowujiagongxiuli_heji_xiaoshoue (Double miandi_huowujiagongxiuli_heji_xiaoshoue) {
	this.miandi_huowujiagongxiuli_heji_xiaoshoue=miandi_huowujiagongxiuli_heji_xiaoshoue;
}

public Double getMiandi_huowujiagongxiuli_heji_xiaoshoue () {
return this.miandi_huowujiagongxiuli_heji_xiaoshoue;
}

public void setMiandi_fu_bu_wu_qita_xiaoshoue (Double miandi_fu_bu_wu_qita_xiaoshoue) {
	this.miandi_fu_bu_wu_qita_xiaoshoue=miandi_fu_bu_wu_qita_xiaoshoue;
}

public Double getMiandi_fu_bu_wu_qita_xiaoshoue () {
return this.miandi_fu_bu_wu_qita_xiaoshoue;
}

public void setMiandi_fu_bu_wu_weikaipiao_xiaoshoue (Double miandi_fu_bu_wu_weikaipiao_xiaoshoue) {
	this.miandi_fu_bu_wu_weikaipiao_xiaoshoue=miandi_fu_bu_wu_weikaipiao_xiaoshoue;
}

public Double getMiandi_fu_bu_wu_weikaipiao_xiaoshoue () {
return this.miandi_fu_bu_wu_weikaipiao_xiaoshoue;
}

public void setMiandi_fu_bu_wu_heji_xiaoshoue (Double miandi_fu_bu_wu_heji_xiaoshoue) {
	this.miandi_fu_bu_wu_heji_xiaoshoue=miandi_fu_bu_wu_heji_xiaoshoue;
}

public Double getMiandi_fu_bu_wu_heji_xiaoshoue () {
return this.miandi_fu_bu_wu_heji_xiaoshoue;
}

public void setMiandi_fu_bu_wu_heji_jiashuiheji (Double miandi_fu_bu_wu_heji_jiashuiheji) {
	this.miandi_fu_bu_wu_heji_jiashuiheji=miandi_fu_bu_wu_heji_jiashuiheji;
}

public Double getMiandi_fu_bu_wu_heji_jiashuiheji () {
return this.miandi_fu_bu_wu_heji_jiashuiheji;
}

public void setMiandi_fu_bu_wu_shijikouchu (Double miandi_fu_bu_wu_shijikouchu) {
	this.miandi_fu_bu_wu_shijikouchu=miandi_fu_bu_wu_shijikouchu;
}

public Double getMiandi_fu_bu_wu_shijikouchu () {
return this.miandi_fu_bu_wu_shijikouchu;
}

public void setMiandi_fu_bu_wu_kouchuhou_xiaoshoue (Double miandi_fu_bu_wu_kouchuhou_xiaoshoue) {
	this.miandi_fu_bu_wu_kouchuhou_xiaoshoue=miandi_fu_bu_wu_kouchuhou_xiaoshoue;
}

public Double getMiandi_fu_bu_wu_kouchuhou_xiaoshoue () {
return this.miandi_fu_bu_wu_kouchuhou_xiaoshoue;
}

public void setMianshui_huowujiagong_shuikong_xiaoshoue (Double mianshui_huowujiagong_shuikong_xiaoshoue) {
	this.mianshui_huowujiagong_shuikong_xiaoshoue=mianshui_huowujiagong_shuikong_xiaoshoue;
}

public Double getMianshui_huowujiagong_shuikong_xiaoshoue () {
return this.mianshui_huowujiagong_shuikong_xiaoshoue;
}

public void setMianshui_huowujiagong_shuikong_xiaoxiangshuie (Double mianshui_huowujiagong_shuikong_xiaoxiangshuie) {
	this.mianshui_huowujiagong_shuikong_xiaoxiangshuie=mianshui_huowujiagong_shuikong_xiaoxiangshuie;
}

public Double getMianshui_huowujiagong_shuikong_xiaoxiangshuie () {
return this.mianshui_huowujiagong_shuikong_xiaoxiangshuie;
}

public void setMianshui_huowujiagong_qita_xiaoshuoe (Double mianshui_huowujiagong_qita_xiaoshuoe) {
	this.mianshui_huowujiagong_qita_xiaoshuoe=mianshui_huowujiagong_qita_xiaoshuoe;
}

public Double getMianshui_huowujiagong_qita_xiaoshuoe () {
return this.mianshui_huowujiagong_qita_xiaoshuoe;
}

public void setMianshui_huowujiagong_weikaipiao_xiaoshoue (Double mianshui_huowujiagong_weikaipiao_xiaoshoue) {
	this.mianshui_huowujiagong_weikaipiao_xiaoshoue=mianshui_huowujiagong_weikaipiao_xiaoshoue;
}

public Double getMianshui_huowujiagong_weikaipiao_xiaoshoue () {
return this.mianshui_huowujiagong_weikaipiao_xiaoshoue;
}

public void setMianshui_huowujiagong_heji_xiaoshoue (Double mianshui_huowujiagong_heji_xiaoshoue) {
	this.mianshui_huowujiagong_heji_xiaoshoue=mianshui_huowujiagong_heji_xiaoshoue;
}

public Double getMianshui_huowujiagong_heji_xiaoshoue () {
return this.mianshui_huowujiagong_heji_xiaoshoue;
}

public void setMianshui_fu_bu_wu_qita_xiaoshoue (Double mianshui_fu_bu_wu_qita_xiaoshoue) {
	this.mianshui_fu_bu_wu_qita_xiaoshoue=mianshui_fu_bu_wu_qita_xiaoshoue;
}

public Double getMianshui_fu_bu_wu_qita_xiaoshoue () {
return this.mianshui_fu_bu_wu_qita_xiaoshoue;
}

public void setMianshui_fu_bu_wu_weikaipiao_xiaoshoue (Double mianshui_fu_bu_wu_weikaipiao_xiaoshoue) {
	this.mianshui_fu_bu_wu_weikaipiao_xiaoshoue=mianshui_fu_bu_wu_weikaipiao_xiaoshoue;
}

public Double getMianshui_fu_bu_wu_weikaipiao_xiaoshoue () {
return this.mianshui_fu_bu_wu_weikaipiao_xiaoshoue;
}

public void setMianshui_fu_bu_wu_heji_xiaoshoue (Double mianshui_fu_bu_wu_heji_xiaoshoue) {
	this.mianshui_fu_bu_wu_heji_xiaoshoue=mianshui_fu_bu_wu_heji_xiaoshoue;
}

public Double getMianshui_fu_bu_wu_heji_xiaoshoue () {
return this.mianshui_fu_bu_wu_heji_xiaoshoue;
}

public void setMianshui_fu_bu_wu_heji_jiashuiheji (Double mianshui_fu_bu_wu_heji_jiashuiheji) {
	this.mianshui_fu_bu_wu_heji_jiashuiheji=mianshui_fu_bu_wu_heji_jiashuiheji;
}

public Double getMianshui_fu_bu_wu_heji_jiashuiheji () {
return this.mianshui_fu_bu_wu_heji_jiashuiheji;
}

public void setMianshui_fu_bu_wu_shijikouchu (Double mianshui_fu_bu_wu_shijikouchu) {
	this.mianshui_fu_bu_wu_shijikouchu=mianshui_fu_bu_wu_shijikouchu;
}

public Double getMianshui_fu_bu_wu_shijikouchu () {
return this.mianshui_fu_bu_wu_shijikouchu;
}

public void setMianshui_fu_bu_wu_kouchuhou_xiaoshoue (Double mianshui_fu_bu_wu_kouchuhou_xiaoshoue) {
	this.mianshui_fu_bu_wu_kouchuhou_xiaoshoue=mianshui_fu_bu_wu_kouchuhou_xiaoshoue;
}

public Double getMianshui_fu_bu_wu_kouchuhou_xiaoshoue () {
return this.mianshui_fu_bu_wu_kouchuhou_xiaoshoue;
}


}
